// Generated by AI on 05/10/2026
import { useState } from 'react';
import {
  Box,
  Typography,
  TextField,
  Paper,
  Table,
  TableHead,
  TableRow,
  TableCell,
  TableBody,
  Chip,
  Card,
  CardContent,
  Stack,
} from '@mui/material';
import { useNavigate } from 'react-router-dom';
import { usePendingSubmissions, useParticipants, useProgramStats } from '../api/adminApi';

export default function AdminDashboardPage() {
  const [search, setSearch] = useState('');
  const { data: pending } = usePendingSubmissions();
  const { data: participants } = useParticipants(search || undefined);
  const { data: stats } = useProgramStats();
  const navigate = useNavigate();

  return (
    <Box sx={{ maxWidth: 1000, mx: 'auto', p: 3 }}>
      <Typography variant="h4" gutterBottom>
        Admin Dashboard
      </Typography>

      {stats && (
        <Stack direction="row" spacing={2} sx={{ mb: 3 }}>
          <Card sx={{ minWidth: 150 }}>
            <CardContent>
              <Typography variant="h5">{stats.totalParticipants}</Typography>
              <Typography variant="body2" color="text.secondary">
                Total Participants
              </Typography>
            </CardContent>
          </Card>
          <Card sx={{ minWidth: 150 }}>
            <CardContent>
              <Typography variant="h5">{stats.wayfinderPercentage}%</Typography>
              <Typography variant="body2" color="text.secondary">
                Wayfinder+
              </Typography>
            </CardContent>
          </Card>
          <Card sx={{ minWidth: 150 }}>
            <CardContent>
              <Typography variant="h5">{stats.pendingReviews}</Typography>
              <Typography variant="body2" color="text.secondary">
                Pending Reviews
              </Typography>
            </CardContent>
          </Card>
          {Object.entries(stats.levelCounts).map(([level, count]) => (
            <Card key={level} sx={{ minWidth: 120 }}>
              <CardContent>
                <Typography variant="h6">{count}</Typography>
                <Typography variant="body2" color="text.secondary">
                  {level}
                </Typography>
              </CardContent>
            </Card>
          ))}
        </Stack>
      )}

      <Typography variant="h6" sx={{ mb: 1 }}>
        Pending Reviews
      </Typography>
      <Paper sx={{ mb: 3 }}>
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell>User ID</TableCell>
              <TableCell>Level</TableCell>
              <TableCell>Submitted</TableCell>
              <TableCell>Action</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {pending?.map((sub) => (
              <TableRow key={sub.id}>
                <TableCell>{sub.userId}</TableCell>
                <TableCell>{sub.level}</TableCell>
                <TableCell>
                  {sub.submittedAt
                    ? new Date(sub.submittedAt).toLocaleDateString()
                    : '—'}
                </TableCell>
                <TableCell>
                  <Chip
                    label="Review"
                    color="primary"
                    size="small"
                    onClick={() => navigate(`/admin/review/${sub.userId}`)}
                    clickable
                  />
                </TableCell>
              </TableRow>
            ))}
            {(!pending || pending.length === 0) && (
              <TableRow>
                <TableCell colSpan={4} align="center">
                  No pending reviews
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </Paper>

      <Typography variant="h6" sx={{ mb: 1 }}>
        Participants
      </Typography>
      <TextField
        size="small"
        placeholder="Search by name, email, or team..."
        value={search}
        onChange={(e) => setSearch(e.target.value)}
        sx={{ mb: 2, width: 400 }}
      />
      <Paper>
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell>Name</TableCell>
              <TableCell>Email</TableCell>
              <TableCell>Level</TableCell>
              <TableCell>Team</TableCell>
              <TableCell>Action</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {participants?.map((p) => (
              <TableRow key={p.userId}>
                <TableCell>{p.displayName}</TableCell>
                <TableCell>{p.email}</TableCell>
                <TableCell>
                  <Chip label={p.currentLevel} size="small" />
                </TableCell>
                <TableCell>{p.team}</TableCell>
                <TableCell>
                  <Chip
                    label="View"
                    size="small"
                    onClick={() =>
                      navigate(`/admin/participant/${p.userId}`)
                    }
                    clickable
                  />
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Paper>
    </Box>
  );
}
