// Generated by AI on 05/10/2026
// Modified by AI on 05/11/2026. Edit #1.
import { useState } from 'react';
import { Box, Typography, Button, Stack, Alert, Paper, Snackbar, TextField, List, ListItem, ListItemText, Chip } from '@mui/material';
import type { BadgeLevel } from '../types';
import { useMe, useCriteria, useEvidence, useTrainingLinks, useSaveEvidence, useSubmitLevel, useActivityLogs, useAddActivityLog } from '../api/participantApi';
import BadgeCard from '../components/BadgeCard';
import ProgressBar from '../components/ProgressBar';
import CriteriaChecklist from '../components/CriteriaChecklist';
import TrainingLinkList from '../components/TrainingLinkList';

const allLevels: BadgeLevel[] = ['Greenhorn', 'Wayfinder', 'TrailGuide', 'Pioneer'];

export default function DashboardPage() {
  const [submitSuccess, setSubmitSuccess] = useState(false);
  const { data: me } = useMe();
  const { data: criteria } = useCriteria();
  const { data: evidence } = useEvidence();
  const { data: trainingLinks } = useTrainingLinks(me?.currentLevel ?? 'Greenhorn');
  const saveEvidence = useSaveEvidence();
  const submitLevel = useSubmitLevel();

  if (!me) return null;

  const approvedCount = evidence?.filter((e) => e.status === 'Approved').length ?? 0;
  const totalCriteria = criteria?.length ?? 0;

  const allHaveEvidence =
    criteria?.every((c) =>
      evidence?.some((e) => e.criterionId === c.id && e.evidenceLinks.length > 0)
    ) ?? false;

  const isSubmitted = evidence?.some((e) => e.status === 'EvidenceSubmitted') ?? false;
  const hasRejected = evidence?.some((e) => e.status === 'Rejected') ?? false;

  const handleSave = (criterionId: string, links: string[], notes: string) => {
    saveEvidence.mutate({ criterionId, data: { evidenceLinks: links, notes } });
  };

  const handleSubmit = () => {
    submitLevel.mutate(undefined, {
      onSuccess: () => setSubmitSuccess(true),
    });
  };

  return (
    <Box sx={{ maxWidth: 900, mx: 'auto', p: 3 }}>
      <Typography variant="h4" gutterBottom>
        AI Trail Dashboard
      </Typography>
      <Typography variant="body1" sx={{ mb: 3 }}>
        Welcome, {me.displayName}
      </Typography>

      <Stack direction="row" spacing={2} sx={{ mb: 3, overflowX: 'auto' }}>
        {allLevels.map((level) => (
          <BadgeCard
            key={level}
            level={level}
            isCurrentLevel={level === me.currentLevel}
          />
        ))}
      </Stack>

      {me.currentLevel !== 'Pioneer' && (
        <>
          <ProgressBar completed={approvedCount} total={totalCriteria} />

          <Typography variant="h6" sx={{ mb: 2 }}>
            Exit Criteria — {me.currentLevel === 'TrailGuide' ? 'Trail Guide' : me.currentLevel}
          </Typography>

          {hasRejected && (
            <Alert severity="warning" sx={{ mb: 2 }}>
              Some evidence was rejected. Update the rejected items and resubmit.
            </Alert>
          )}

          <CriteriaChecklist
            criteria={criteria ?? []}
            evidence={evidence ?? []}
            onSave={handleSave}
          />

          <Box sx={{ mt: 3, display: 'flex', gap: 2 }}>
            <Button
              variant="contained"
              color="primary"
              disabled={!allHaveEvidence || isSubmitted}
              onClick={handleSubmit}
            >
              {isSubmitted ? 'Submitted for Review' : 'Submit for Review'}
            </Button>
          </Box>

          {submitLevel.isError && (
            <Alert severity="error" sx={{ mt: 2 }}>
              {(submitLevel.error as Error).message ?? 'Submission failed.'}
            </Alert>
          )}
        </>
      )}

      {me.currentLevel === 'Pioneer' && <PioneerSection />}

      {trainingLinks && trainingLinks.length > 0 && (
        <Paper sx={{ p: 2, mt: 4 }}>
          <Typography variant="h6" gutterBottom>
            Training Resources
          </Typography>
          <TrainingLinkList links={trainingLinks} />
        </Paper>
      )}

      <Snackbar
        open={submitSuccess}
        autoHideDuration={4000}
        onClose={() => setSubmitSuccess(false)}
        message="Level submitted for review successfully!"
      />
    </Box>
  );
}

function PioneerSection() {
  const { data: logs } = useActivityLogs();
  const addLog = useAddActivityLog();
  const [description, setDescription] = useState('');
  const [category, setCategory] = useState('');

  const handleAddLog = () => {
    if (!description.trim()) return;
    addLog.mutate(
      { description, category: category || 'General' },
      {
        onSuccess: () => {
          setDescription('');
          setCategory('');
        },
      }
    );
  };

  return (
    <>
      <Alert severity="success" sx={{ mb: 3 }}>
        You have reached the highest level — Pioneer! Continue leading and innovating.
      </Alert>

      <Paper sx={{ p: 2, mb: 3 }}>
        <Typography variant="h6" gutterBottom>
          Pioneer Expectations
        </Typography>
        <List dense>
          <ListItem><ListItemText primary="Pilot new AI tooling and practices; run viability pilots" /></ListItem>
          <ListItem><ListItemText primary="Monthly create and publish articles for the engineering group" /></ListItem>
          <ListItem><ListItemText primary="Collaborate with Product, UX, PMO to accelerate AI utilization" /></ListItem>
          <ListItem><ListItemText primary="Create and present content for the AI Trail monthly meeting" /></ListItem>
        </List>
      </Paper>

      <Paper sx={{ p: 2, mb: 3 }}>
        <Typography variant="h6" gutterBottom>
          Activity Log
        </Typography>
        <Stack direction="row" spacing={1} sx={{ mb: 2 }}>
          <TextField
            size="small"
            placeholder="Description of activity..."
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            sx={{ flexGrow: 1 }}
          />
          <TextField
            size="small"
            placeholder="Category"
            value={category}
            onChange={(e) => setCategory(e.target.value)}
            sx={{ width: 150 }}
          />
          <Button variant="contained" size="small" onClick={handleAddLog} disabled={!description.trim()}>
            Log Activity
          </Button>
        </Stack>
        {logs && logs.length > 0 && (
          <List dense>
            {logs.map((log) => (
              <ListItem key={log.id}>
                <ListItemText
                  primary={log.description}
                  secondary={`${new Date(log.date).toLocaleDateString()} — ${log.category}`}
                />
                <Chip label={log.category} size="small" />
              </ListItem>
            ))}
          </List>
        )}
      </Paper>
    </>
  );
}
