// Generated by AI on 05/10/2026
import { useParams, useNavigate } from 'react-router-dom';
import {
  Box,
  Typography,
  Button,
  Paper,
  Chip,
  List,
  ListItem,
  ListItemText,
  Stack,
} from '@mui/material';
import { useParticipantDetail, useParticipantEvidence } from '../api/adminApi';
import BadgeCard from '../components/BadgeCard';
import SubmissionStatus from '../components/SubmissionStatus';
import { InMemoryStorage_GetExitCriteria } from '../data/exitCriteria';
import type { BadgeLevel } from '../types';

const allLevels: BadgeLevel[] = ['Greenhorn', 'Wayfinder', 'TrailGuide', 'Pioneer'];

export default function ParticipantDetailPage() {
  const { userId } = useParams<{ userId: string }>();
  const navigate = useNavigate();
  const { data: participant } = useParticipantDetail(userId ?? '');
  const { data: evidence } = useParticipantEvidence(userId ?? '');

  if (!participant || !userId) return null;

  const criteria = InMemoryStorage_GetExitCriteria(participant.currentLevel);

  return (
    <Box sx={{ maxWidth: 800, mx: 'auto', p: 3 }}>
      <Button onClick={() => navigate('/admin')} sx={{ mb: 2 }}>
        ← Back to Admin
      </Button>
      <Typography variant="h5" gutterBottom>
        {participant.displayName}
      </Typography>
      <Typography variant="body2" color="text.secondary">
        Email: {participant.email} | Team: {participant.team} | Guild:{' '}
        {participant.guildName || '—'}
      </Typography>

      <Stack direction="row" spacing={2} sx={{ my: 3 }}>
        {allLevels.map((level) => (
          <BadgeCard
            key={level}
            level={level}
            isCurrentLevel={level === participant.currentLevel}
          />
        ))}
      </Stack>

      <Typography variant="h6" sx={{ mb: 1 }}>
        Current Level Criteria
      </Typography>
      {criteria.map((criterion) => {
        const sub = evidence?.find((e) => e.criterionId === criterion.id);
        return (
          <Paper key={criterion.id} sx={{ mb: 2, p: 2 }}>
            <Typography variant="subtitle1">
              #{criterion.criterionNumber} — {criterion.title}
            </Typography>
            {sub ? (
              <>
                <SubmissionStatus status={sub.status} feedback={sub.adminFeedback} />
                <List dense>
                  {sub.evidenceLinks.map((link, idx) => (
                    <ListItem key={idx} disablePadding>
                      <ListItemText
                        primary={
                          <a href={link} target="_blank" rel="noopener noreferrer">
                            {link}
                          </a>
                        }
                      />
                    </ListItem>
                  ))}
                </List>
              </>
            ) : (
              <Chip label="Not Started" size="small" />
            )}
          </Paper>
        );
      })}
    </Box>
  );
}
