// Generated by AI on 05/10/2026
// Modified by AI on 05/11/2026. Edit #1.
import { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  Box,
  Typography,
  Button,
  Paper,
  List,
  ListItem,
  ListItemText,
  TextField,
  Alert,
  Divider,
  Stack,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  DialogActions,
} from '@mui/material';
import {
  useParticipantDetail,
  useParticipantEvidence,
  useApproveEvidence,
  useRejectEvidence,
  useAdvanceParticipant,
} from '../api/adminApi';
import SubmissionStatus from '../components/SubmissionStatus';
import { InMemoryStorage_GetExitCriteria } from '../data/exitCriteria';

export default function ReviewSubmissionPage() {
  const { userId } = useParams<{ userId: string }>();
  const navigate = useNavigate();
  const { data: participant } = useParticipantDetail(userId ?? '');
  const { data: evidence } = useParticipantEvidence(userId ?? '');
  const approveEvidence = useApproveEvidence();
  const rejectEvidence = useRejectEvidence();
  const advanceParticipant = useAdvanceParticipant();
  const [rejectFeedback, setRejectFeedback] = useState<Record<string, string>>({});
  const [advanceDialogOpen, setAdvanceDialogOpen] = useState(false);

  if (!participant || !userId) return null;

  const criteria = InMemoryStorage_GetExitCriteria(participant.currentLevel);
  const allApproved = criteria.every((c) =>
    evidence?.some((e) => e.criterionId === c.id && e.status === 'Approved')
  );

  const handleApprove = (criterionId: string) => {
    approveEvidence.mutate({ userId, criterionId });
  };

  const handleReject = (criterionId: string) => {
    const feedback = rejectFeedback[criterionId];
    if (!feedback?.trim()) return;
    rejectEvidence.mutate({ userId, criterionId, data: { feedback } });
  };

  const handleAdvance = () => {
    advanceParticipant.mutate(userId, {
      onSuccess: () => navigate('/admin'),
    });
    setAdvanceDialogOpen(false);
  };

  return (
    <Box sx={{ maxWidth: 800, mx: 'auto', p: 3 }}>
      <Button onClick={() => navigate('/admin')} sx={{ mb: 2 }}>
        ← Back to Admin
      </Button>
      <Typography variant="h5" gutterBottom>
        Review: {participant.displayName}
      </Typography>
      <Typography variant="body2" color="text.secondary" gutterBottom>
        Current Level: {participant.currentLevel} | Email: {participant.email}
      </Typography>

      <List>
        {criteria.map((criterion) => {
          const sub = evidence?.find((e) => e.criterionId === criterion.id);
          return (
            <Paper key={criterion.id} sx={{ mb: 2, p: 2 }}>
              <Typography variant="subtitle1">
                #{criterion.criterionNumber} — {criterion.title}
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
                {criterion.description}
              </Typography>

              {sub && (
                <>
                  <SubmissionStatus status={sub.status} feedback={sub.adminFeedback} />
                  <Typography variant="body2" sx={{ mt: 1 }}>
                    <strong>Evidence Links:</strong>
                  </Typography>
                  <List dense>
                    {sub.evidenceLinks.map((link, idx) => (
                      <ListItem key={idx} disablePadding>
                        <ListItemText
                          primary={
                            <a href={link} target="_blank" rel="noopener noreferrer">
                              {link}
                            </a>
                          }
                        />
                      </ListItem>
                    ))}
                  </List>
                  {sub.notes && (
                    <Typography variant="body2">
                      <strong>Notes:</strong> {sub.notes}
                    </Typography>
                  )}

                  <Divider sx={{ my: 1 }} />
                  <Stack direction="row" spacing={1} alignItems="center">
                    <Button
                      variant="contained"
                      color="success"
                      size="small"
                      disabled={sub.status === 'Approved'}
                      onClick={() => handleApprove(criterion.id)}
                    >
                      Approve
                    </Button>
                    <TextField
                      size="small"
                      placeholder="Rejection feedback (required)"
                      value={rejectFeedback[criterion.id] ?? ''}
                      onChange={(e) =>
                        setRejectFeedback((prev) => ({
                          ...prev,
                          [criterion.id]: e.target.value,
                        }))
                      }
                      sx={{ flexGrow: 1 }}
                    />
                    <Button
                      variant="outlined"
                      color="error"
                      size="small"
                      disabled={
                        sub.status === 'Rejected' ||
                        !rejectFeedback[criterion.id]?.trim()
                      }
                      onClick={() => handleReject(criterion.id)}
                    >
                      Reject
                    </Button>
                  </Stack>
                </>
              )}

              {!sub && (
                <Alert severity="info" sx={{ mt: 1 }}>
                  No evidence submitted yet.
                </Alert>
              )}
            </Paper>
          );
        })}
      </List>

      <Button
        variant="contained"
        color="primary"
        disabled={!allApproved}
        onClick={() => setAdvanceDialogOpen(true)}
        sx={{ mt: 2 }}
      >
        Approve Level Advancement
      </Button>

      <Dialog open={advanceDialogOpen} onClose={() => setAdvanceDialogOpen(false)}>
        <DialogTitle>Confirm Level Advancement</DialogTitle>
        <DialogContent>
          <DialogContentText>
            Advance {participant.displayName} from {participant.currentLevel} to the next level?
            This action cannot be undone.
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setAdvanceDialogOpen(false)}>Cancel</Button>
          <Button onClick={handleAdvance} variant="contained" color="primary">
            Confirm
          </Button>
        </DialogActions>
      </Dialog>

      {advanceParticipant.isError && (
        <Alert severity="error" sx={{ mt: 2 }}>
          {(advanceParticipant.error as Error).message ?? 'Advancement failed.'}
        </Alert>
      )}
    </Box>
  );
}
