// Generated by AI on 05/12/2026
import { useState, useMemo } from 'react';
import { Box, Typography, TextField, CircularProgress } from '@mui/material';
import { useTeamProgress } from '../api/adminApi';
import TeamCard from '../components/TeamCard';

export default function TeamProgressPage() {
  const { data: teams, isLoading } = useTeamProgress();
  const [filter, setFilter] = useState('');

  const filteredTeams = useMemo(() => {
    if (!teams) return [];
    if (!filter.trim()) return teams;
    const lower = filter.toLowerCase();
    return teams.filter((t) => t.teamName.toLowerCase().includes(lower));
  }, [teams, filter]);

  if (isLoading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', mt: 10 }}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <Box sx={{ maxWidth: 1000, mx: 'auto', p: 3 }}>
      <Typography variant="h4" gutterBottom>
        Team Progress
      </Typography>

      <TextField
        size="small"
        placeholder="Filter by team name..."
        value={filter}
        onChange={(e) => setFilter(e.target.value)}
        sx={{ mb: 3, width: 400 }}
      />

      {filteredTeams.length === 0 ? (
        <Typography color="text.secondary">No teams found.</Typography>
      ) : (
        filteredTeams.map((team) => <TeamCard key={team.teamName} team={team} />)
      )}
    </Box>
  );
}
