// Generated by AI on 05/10/2026
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import apiClient from './client';
import type {
  Participant,
  EvidenceSubmission,
  LevelSubmission,
  ProgramStats,
  RejectRequest,
  BadgeLevel,
} from '../types';

export function usePendingSubmissions() {
  return useQuery<LevelSubmission[]>({
    queryKey: ['admin', 'pending'],
    queryFn: () => apiClient.get('/admin/pending').then((r) => r.data),
  });
}

export function useParticipants(search?: string) {
  return useQuery<Participant[]>({
    queryKey: ['admin', 'participants', search],
    queryFn: () =>
      apiClient
        .get('/admin/participants', { params: { search } })
        .then((r) => r.data),
  });
}

export function useParticipantDetail(userId: string) {
  return useQuery<Participant>({
    queryKey: ['admin', 'participant', userId],
    queryFn: () =>
      apiClient.get(`/admin/participants/${userId}`).then((r) => r.data),
    enabled: !!userId,
  });
}

export function useParticipantEvidence(userId: string, level?: BadgeLevel) {
  return useQuery<EvidenceSubmission[]>({
    queryKey: ['admin', 'evidence', userId, level],
    queryFn: () =>
      apiClient
        .get(`/admin/participants/${userId}/evidence`, {
          params: level ? { level } : undefined,
        })
        .then((r) => r.data),
    enabled: !!userId,
  });
}

export function useProgramStats() {
  return useQuery<ProgramStats>({
    queryKey: ['admin', 'stats'],
    queryFn: () => apiClient.get('/admin/stats').then((r) => r.data),
  });
}

export function useApproveEvidence() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({
      userId,
      criterionId,
    }: {
      userId: string;
      criterionId: string;
    }) => apiClient.post(`/admin/evidence/${userId}/${criterionId}/approve`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['admin'] });
    },
  });
}

export function useRejectEvidence() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({
      userId,
      criterionId,
      data,
    }: {
      userId: string;
      criterionId: string;
      data: RejectRequest;
    }) =>
      apiClient.post(`/admin/evidence/${userId}/${criterionId}/reject`, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['admin'] });
    },
  });
}

export function useAdvanceParticipant() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (userId: string) =>
      apiClient.post(`/admin/participants/${userId}/advance`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['admin'] });
    },
  });
}
