// Generated by AI on 05/10/2026
// Modified by AI on 05/11/2026. Edit #1.
import axios from 'axios';

const apiClient = axios.create({
  baseURL: '/api',
  withCredentials: true,
  xsrfCookieName: 'XSRF-TOKEN',
  xsrfHeaderName: 'X-XSRF-TOKEN',
});

export default apiClient;
