// Generated by AI on 05/10/2026
// Modified by AI on 05/11/2026. Edit #1.
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import apiClient from './client';
import type {
  Participant,
  ExitCriterion,
  EvidenceSubmission,
  LevelSubmission,
  TrainingLink,
  SaveEvidenceRequest,
  BadgeLevel,
  PioneerActivityLog,
  AddActivityLogRequest,
} from '../types';

export function useMe() {
  return useQuery<Participant>({
    queryKey: ['participant', 'me'],
    queryFn: () => apiClient.get('/participant/me').then((r) => r.data),
  });
}

export function useCriteria() {
  return useQuery<ExitCriterion[]>({
    queryKey: ['participant', 'criteria'],
    queryFn: () => apiClient.get('/participant/me/criteria').then((r) => r.data),
  });
}

export function useEvidence() {
  return useQuery<EvidenceSubmission[]>({
    queryKey: ['participant', 'evidence'],
    queryFn: () => apiClient.get('/participant/me/evidence').then((r) => r.data),
  });
}

export function useHistory() {
  return useQuery<LevelSubmission[]>({
    queryKey: ['participant', 'history'],
    queryFn: () => apiClient.get('/participant/me/history').then((r) => r.data),
  });
}

export function useTrainingLinks(level: BadgeLevel) {
  return useQuery<TrainingLink[]>({
    queryKey: ['training-links', level],
    queryFn: () =>
      apiClient.get(`/training-links/${level}`).then((r) => r.data),
  });
}

export function useSaveEvidence() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({
      criterionId,
      data,
    }: {
      criterionId: string;
      data: SaveEvidenceRequest;
    }) => apiClient.put(`/participant/me/evidence/${criterionId}`, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['participant', 'evidence'] });
    },
  });
}

export function useSubmitLevel() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: () => apiClient.post('/participant/me/submit'),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['participant'] });
    },
  });
}

export function useActivityLogs() {
  return useQuery<PioneerActivityLog[]>({
    queryKey: ['participant', 'activity-log'],
    queryFn: () => apiClient.get('/participant/activity-log').then((r) => r.data),
  });
}

export function useAddActivityLog() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (data: AddActivityLogRequest) =>
      apiClient.post('/participant/activity-log', data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['participant', 'activity-log'] });
    },
  });
}
