// Generated by AI on 05/10/2026
// Modified by AI on 05/12/2026. Edit #1.
using System.Security.Claims;
using AiTrailTracker.Api.Models;
using AiTrailTracker.Api.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AiTrailTracker.Api.Controllers;

[ApiController]
[Route("api/admin")]
[Authorize(Policy = "AdminOnly")]
public class AdminController : ControllerBase
{
    private readonly IAdminService _adminService;

    public AdminController(IAdminService adminService)
    {
        _adminService = adminService;
    }

    private string GetAdminUserId()
    {
        return User.FindFirstValue("oid") ?? User.FindFirstValue(ClaimTypes.NameIdentifier) ?? "unknown";
    }

    [HttpGet("pending")]
    public async Task<IActionResult> GetPending()
    {
        var pending = await _adminService.GetPendingSubmissionsAsync();
        return Ok(pending);
    }

    [HttpGet("participants")]
    public async Task<IActionResult> GetParticipants([FromQuery] string? search)
    {
        var participants = await _adminService.GetAllParticipantsAsync(search);
        return Ok(participants);
    }

    [HttpGet("participants/{userId}")]
    public async Task<IActionResult> GetParticipant(string userId)
    {
        var participant = await _adminService.GetParticipantAsync(userId);
        if (participant == null) return NotFound();
        return Ok(participant);
    }

    [HttpGet("participants/{userId}/evidence")]
    public async Task<IActionResult> GetParticipantEvidence(string userId, [FromQuery] BadgeLevel? level)
    {
        var participant = await _adminService.GetParticipantAsync(userId);
        if (participant == null) return NotFound();

        var targetLevel = level ?? participant.CurrentLevel;
        var evidence = await _adminService.GetEvidenceForUserLevelAsync(userId, targetLevel);
        return Ok(evidence);
    }

    [HttpPost("evidence/{userId}/{criterionId}/approve")]
    public async Task<IActionResult> ApproveEvidence(string userId, string criterionId)
    {
        try
        {
            await _adminService.ApproveEvidenceAsync(userId, criterionId, GetAdminUserId());
            return Ok(new { message = "Evidence approved." });
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { error = ex.Message });
        }
    }

    [HttpPost("evidence/{userId}/{criterionId}/reject")]
    public async Task<IActionResult> RejectEvidence(string userId, string criterionId, [FromBody] RejectRequest request)
    {
        try
        {
            await _adminService.RejectEvidenceAsync(userId, criterionId, GetAdminUserId(), request.Feedback);
            return Ok(new { message = "Evidence rejected." });
        }
        catch (Exception ex) when (ex is InvalidOperationException or ArgumentException)
        {
            return BadRequest(new { error = ex.Message });
        }
    }

    [HttpPost("participants/{userId}/advance")]
    public async Task<IActionResult> AdvanceParticipant(string userId)
    {
        try
        {
            await _adminService.AdvanceParticipantAsync(userId, GetAdminUserId());
            return Ok(new { message = "Participant advanced to next level." });
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { error = ex.Message });
        }
    }

    [HttpGet("stats")]
    public async Task<IActionResult> GetStats()
    {
        var stats = await _adminService.GetProgramStatsAsync();
        return Ok(stats);
    }

    [HttpGet("team-progress")]
    public async Task<IActionResult> GetTeamProgress()
    {
        var progress = await _adminService.GetTeamProgressAsync();
        return Ok(progress);
    }
}
