// Generated by AI on 05/10/2026
// Modified by AI on 05/11/2026. Edit #1.
using System.Security.Claims;
using AiTrailTracker.Api.Models;
using AiTrailTracker.Api.Services;
using AiTrailTracker.Api.Validation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AiTrailTracker.Api.Controllers;

[ApiController]
[Route("api/participant")]
[Authorize]
public class ParticipantController : ControllerBase
{
    private readonly IParticipantService _service;

    public ParticipantController(IParticipantService service)
    {
        _service = service;
    }

    private (string UserId, string DisplayName, string Email) GetCurrentUser()
    {
        var userId = User.FindFirstValue("oid") ?? User.FindFirstValue(ClaimTypes.NameIdentifier) ?? "unknown";
        var displayName = User.FindFirstValue(ClaimTypes.Name) ?? "Unknown";
        var email = User.FindFirstValue(ClaimTypes.Email) ?? "";
        return (userId, displayName, email);
    }

    [HttpGet("me")]
    public async Task<IActionResult> GetMe()
    {
        var (userId, displayName, email) = GetCurrentUser();
        var participant = await _service.GetOrCreateParticipantAsync(userId, displayName, email);
        return Ok(participant);
    }

    [HttpGet("me/criteria")]
    public async Task<IActionResult> GetCriteria()
    {
        var (userId, displayName, email) = GetCurrentUser();
        var participant = await _service.GetOrCreateParticipantAsync(userId, displayName, email);
        var criteria = await _service.GetCriteriaForLevelAsync(participant.CurrentLevel);
        return Ok(criteria);
    }

    [HttpGet("me/evidence")]
    public async Task<IActionResult> GetEvidence()
    {
        var (userId, _, _) = GetCurrentUser();
        var evidence = await _service.GetEvidenceForCurrentLevelAsync(userId);
        return Ok(evidence);
    }

    [HttpPut("me/evidence/{criterionId}")]
    public async Task<IActionResult> SaveEvidence(string criterionId, [FromBody] SaveEvidenceRequest request)
    {
        // Validate URL format
        var urlErrors = UrlValidator.ValidateEvidenceLinks(request.EvidenceLinks);
        if (urlErrors.Count > 0)
            return BadRequest(new { errors = urlErrors });

        // Sanitize notes
        var sanitizedNotes = InputSanitizer.SanitizeText(request.Notes);

        var (userId, _, _) = GetCurrentUser();
        try
        {
            await _service.SaveEvidenceAsync(userId, criterionId, request.EvidenceLinks, sanitizedNotes);
            return Ok();
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { error = ex.Message });
        }
    }

    [HttpPost("me/submit")]
    public async Task<IActionResult> SubmitLevel()
    {
        var (userId, _, _) = GetCurrentUser();
        try
        {
            await _service.SubmitLevelForReviewAsync(userId);
            return Ok(new { message = "Level submitted for review." });
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { error = ex.Message });
        }
    }

    [HttpGet("me/history")]
    public async Task<IActionResult> GetHistory()
    {
        var (userId, _, _) = GetCurrentUser();
        var history = await _service.GetLevelHistoryAsync(userId);
        return Ok(history);
    }

    [HttpGet("activity-log")]
    public async Task<IActionResult> GetActivityLog()
    {
        var (userId, _, _) = GetCurrentUser();
        var logs = await _service.GetActivityLogsAsync(userId);
        return Ok(logs);
    }

    [HttpPost("activity-log")]
    public async Task<IActionResult> AddActivityLog([FromBody] AddActivityLogRequest request)
    {
        var (userId, _, _) = GetCurrentUser();
        try
        {
            await _service.AddActivityLogAsync(userId, request.Description, request.Category);
            return Ok(new { message = "Activity logged." });
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { error = ex.Message });
        }
    }
}
