// Generated by AI on 05/10/2026
using AiTrailTracker.Api.Models;
using AiTrailTracker.Api.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AiTrailTracker.Api.Controllers;

[ApiController]
[Route("api/training-links")]
[Authorize]
public class TrainingController : ControllerBase
{
    private readonly IParticipantService _service;

    public TrainingController(IParticipantService service)
    {
        _service = service;
    }

    [HttpGet("{level}")]
    public async Task<IActionResult> GetTrainingLinks(BadgeLevel level)
    {
        var links = await _service.GetTrainingLinksAsync(level);
        return Ok(links);
    }
}
