// Generated by AI on 05/10/2026
// Modified by AI on 05/11/2026. Edit #1.
// Modified by AI on 05/12/2026. Edit #2.
export type BadgeLevel = 'Greenhorn' | 'Wayfinder' | 'TrailGuide' | 'Pioneer';

export type CriterionStatus =
  | 'NotStarted'
  | 'InProgress'
  | 'EvidenceSubmitted'
  | 'Approved'
  | 'Rejected';

export interface Participant {
  userId: string;
  displayName: string;
  email: string;
  team: string;
  guildName: string;
  currentLevel: BadgeLevel;
  isAdmin: boolean;
  createdAt: string;
  lastAdvancementAt: string | null;
}

export interface ExitCriterion {
  id: string;
  level: BadgeLevel;
  criterionNumber: number;
  title: string;
  description: string;
  evidenceType: 'url' | 'text' | 'multi-url';
}

export interface EvidenceSubmission {
  id: string;
  userId: string;
  criterionId: string;
  level: BadgeLevel;
  evidenceLinks: string[];
  notes: string;
  status: CriterionStatus;
  adminFeedback: string | null;
  submittedAt: string | null;
  reviewedAt: string | null;
  reviewedBy: string | null;
}

export interface LevelSubmission {
  id: string;
  userId: string;
  level: BadgeLevel;
  isSubmitted: boolean;
  submittedAt: string | null;
  isApproved: boolean;
  approvedAt: string | null;
  approvedBy: string | null;
}

export interface TrainingLink {
  id: string;
  level: BadgeLevel;
  category: string;
  title: string;
  url: string;
  sortOrder: number;
}

export interface ProgramStats {
  totalParticipants: number;
  levelCounts: Record<string, number>;
  wayfinderPercentage: number;
  pendingReviews: number;
}

export interface SaveEvidenceRequest {
  evidenceLinks: string[];
  notes?: string;
}

export interface RejectRequest {
  feedback: string;
}

export interface PioneerActivityLog {
  id: string;
  userId: string;
  date: string;
  description: string;
  category: string;
}

export interface AddActivityLogRequest {
  description: string;
  category: string;
}

export interface TeamMemberDto {
  userId: string;
  displayName: string;
  currentLevel: string;
  daysAtCurrentLevel: number;
  lastEvidenceDate: string | null;
  isStalled: boolean;
}

export interface TeamProgressDto {
  teamName: string;
  memberCount: number;
  levelCounts: Record<string, number>;
  members: TeamMemberDto[];
}
