// Generated by AI on 05/10/2026
// Modified by AI on 05/11/2026. Edit #1.
namespace AiTrailTracker.Api.Models;

public record SaveEvidenceRequest(List<string> EvidenceLinks, string? Notes);

public record RejectRequest(string Feedback);

public record AddActivityLogRequest(string Description, string Category);

public record ProgramStats(
    int TotalParticipants,
    Dictionary<string, int> LevelCounts,
    double WayfinderPercentage,
    int PendingReviews);
