// Generated by AI on 05/10/2026
namespace AiTrailTracker.Api.Models;

public class EvidenceSubmission
{
    public string Id { get; set; } = string.Empty;
    public string UserId { get; set; } = string.Empty;
    public string CriterionId { get; set; } = string.Empty;
    public BadgeLevel Level { get; set; }
    public List<string> EvidenceLinks { get; set; } = new();
    public string Notes { get; set; } = string.Empty;
    public CriterionStatus Status { get; set; } = CriterionStatus.NotStarted;
    public string? AdminFeedback { get; set; }
    public DateTime? SubmittedAt { get; set; }
    public DateTime? ReviewedAt { get; set; }
    public string? ReviewedBy { get; set; }
}
