// Generated by AI on 05/10/2026
namespace AiTrailTracker.Api.Models;

public class ExitCriterion
{
    public string Id { get; set; } = string.Empty;
    public BadgeLevel Level { get; set; }
    public int CriterionNumber { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string EvidenceType { get; set; } = "url";
}
