// Generated by AI on 05/10/2026
namespace AiTrailTracker.Api.Models;

public class LevelSubmission
{
    public string Id { get; set; } = string.Empty;
    public string UserId { get; set; } = string.Empty;
    public BadgeLevel Level { get; set; }
    public bool IsSubmitted { get; set; }
    public DateTime? SubmittedAt { get; set; }
    public bool IsApproved { get; set; }
    public DateTime? ApprovedAt { get; set; }
    public string? ApprovedBy { get; set; }
}
