// Generated by AI on 05/10/2026
namespace AiTrailTracker.Api.Models;

public class Participant
{
    public string UserId { get; set; } = string.Empty;
    public string DisplayName { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public string Team { get; set; } = string.Empty;
    public string GuildName { get; set; } = string.Empty;
    public BadgeLevel CurrentLevel { get; set; } = BadgeLevel.Greenhorn;
    public bool IsAdmin { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? LastAdvancementAt { get; set; }
}
