// Generated by AI on 05/11/2026
namespace AiTrailTracker.Api.Models;

public class PioneerActivityLog
{
    public string Id { get; set; } = string.Empty;
    public string UserId { get; set; } = string.Empty;
    public DateTime Date { get; set; }
    public string Description { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
}
