// Generated by AI on 05/10/2026
namespace AiTrailTracker.Api.Models;

public class TrainingLink
{
    public string Id { get; set; } = string.Empty;
    public BadgeLevel Level { get; set; }
    public string Category { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string Url { get; set; } = string.Empty;
    public int SortOrder { get; set; }
}
