// Generated by AI on 05/10/2026
import { Card, CardContent, Typography, Chip } from '@mui/material';
import type { BadgeLevel } from '../types';

const badgeColors: Record<BadgeLevel, string> = {
  Greenhorn: '#8bc34a',
  Wayfinder: '#2196f3',
  TrailGuide: '#ff9800',
  Pioneer: '#9c27b0',
};

const badgeDescriptions: Record<BadgeLevel, string> = {
  Greenhorn: 'Learning the basics',
  Wayfinder: 'Independent AI usage',
  TrailGuide: 'Coaching others',
  Pioneer: 'Innovate & Lead',
};

interface BadgeCardProps {
  level: BadgeLevel;
  isCurrentLevel?: boolean;
}

export default function BadgeCard({ level, isCurrentLevel }: BadgeCardProps) {
  return (
    <Card
      sx={{
        border: isCurrentLevel ? `3px solid ${badgeColors[level]}` : undefined,
        opacity: isCurrentLevel ? 1 : 0.6,
        minWidth: 160,
      }}
    >
      <CardContent sx={{ textAlign: 'center' }}>
        <Typography variant="h6" sx={{ color: badgeColors[level] }}>
          {level === 'TrailGuide' ? 'Trail Guide' : level}
        </Typography>
        <Typography variant="body2" color="text.secondary">
          {badgeDescriptions[level]}
        </Typography>
        {isCurrentLevel && (
          <Chip
            label="Current Level"
            size="small"
            sx={{ mt: 1, bgcolor: badgeColors[level], color: '#fff' }}
          />
        )}
      </CardContent>
    </Card>
  );
}
