// Generated by AI on 05/10/2026
import {
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Typography,
  Box,
} from '@mui/material';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import type { ExitCriterion, EvidenceSubmission } from '../types';
import EvidenceInput from './EvidenceInput';
import SubmissionStatus from './SubmissionStatus';

interface CriteriaChecklistProps {
  criteria: ExitCriterion[];
  evidence: EvidenceSubmission[];
  disabled?: boolean;
  onSave: (criterionId: string, links: string[], notes: string) => void;
}

export default function CriteriaChecklist({
  criteria,
  evidence,
  disabled,
  onSave,
}: CriteriaChecklistProps) {
  const getSubmission = (criterionId: string) =>
    evidence.find((e) => e.criterionId === criterionId);

  return (
    <>
      {criteria.map((criterion) => {
        const submission = getSubmission(criterion.id);
        const isLocked =
          disabled ||
          (submission?.status === 'EvidenceSubmitted') ||
          (submission?.status === 'Approved');

        return (
          <Accordion key={criterion.id} defaultExpanded>
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, width: '100%' }}>
                <Typography sx={{ flexGrow: 1 }}>
                  #{criterion.criterionNumber} — {criterion.title}
                </Typography>
                {submission && (
                  <SubmissionStatus
                    status={submission.status}
                    feedback={submission.adminFeedback}
                  />
                )}
              </Box>
            </AccordionSummary>
            <AccordionDetails>
              <EvidenceInput
                criterion={criterion}
                submission={submission}
                disabled={isLocked}
                onSave={onSave}
              />
            </AccordionDetails>
          </Accordion>
        );
      })}
    </>
  );
}
