// Generated by AI on 05/10/2026
// Modified by AI on 05/11/2026. Edit #1.
import { useState } from 'react';
import {
  Box,
  TextField,
  Button,
  IconButton,
  Typography,
} from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import DeleteIcon from '@mui/icons-material/Delete';
import type { ExitCriterion, EvidenceSubmission } from '../types';

function isValidUrl(url: string): boolean {
  try {
    const parsed = new URL(url);
    return parsed.protocol === 'http:' || parsed.protocol === 'https:';
  } catch {
    return false;
  }
}

interface EvidenceInputProps {
  criterion: ExitCriterion;
  submission?: EvidenceSubmission;
  disabled?: boolean;
  onSave: (criterionId: string, links: string[], notes: string) => void;
}

export default function EvidenceInput({
  criterion,
  submission,
  disabled,
  onSave,
}: EvidenceInputProps) {
  const [links, setLinks] = useState<string[]>(
    submission?.evidenceLinks?.length ? submission.evidenceLinks : ['']
  );
  const [notes, setNotes] = useState(submission?.notes ?? '');
  const [linkErrors, setLinkErrors] = useState<(string | null)[]>([]);

  const isMulti = criterion.evidenceType === 'multi-url';

  const validateLinks = (currentLinks: string[]): boolean => {
    const errors = currentLinks.map((link) => {
      if (link.trim() === '') return null;
      return isValidUrl(link) ? null : 'Enter a valid http:// or https:// URL';
    });
    setLinkErrors(errors);
    const nonEmpty = currentLinks.filter((l) => l.trim() !== '');
    return nonEmpty.length > 0 && errors.every((e) => e === null);
  };

  const handleAddLink = () => {
    setLinks([...links, '']);
    setLinkErrors([...linkErrors, null]);
  };
  const handleRemoveLink = (idx: number) => {
    setLinks(links.filter((_, i) => i !== idx));
    setLinkErrors(linkErrors.filter((_, i) => i !== idx));
  };
  const handleLinkChange = (idx: number, value: string) => {
    const updated = [...links];
    updated[idx] = value;
    setLinks(updated);
    // Clear error for this field on change
    const updatedErrors = [...linkErrors];
    updatedErrors[idx] = null;
    setLinkErrors(updatedErrors);
  };

  const handleSave = () => {
    const filtered = links.filter((l) => l.trim() !== '');
    if (!validateLinks(links)) return;
    onSave(criterion.id, filtered, notes);
  };

  const hasErrors = linkErrors.some((e) => e !== null);

  return (
    <Box sx={{ mb: 2 }}>
      <Typography variant="subtitle2">{criterion.title}</Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
        {criterion.description}
      </Typography>

      {links.map((link, idx) => (
        <Box key={idx} sx={{ display: 'flex', gap: 1, mb: 0.5 }}>
          <TextField
            size="small"
            fullWidth
            placeholder="https://..."
            value={link}
            onChange={(e) => handleLinkChange(idx, e.target.value)}
            disabled={disabled}
            error={!!linkErrors[idx]}
            helperText={linkErrors[idx]}
          />
          {isMulti && links.length > 1 && !disabled && (
            <IconButton size="small" onClick={() => handleRemoveLink(idx)}>
              <DeleteIcon fontSize="small" />
            </IconButton>
          )}
        </Box>
      ))}

      {isMulti && !disabled && (
        <Button
          size="small"
          startIcon={<AddIcon />}
          onClick={handleAddLink}
          sx={{ mb: 1 }}
        >
          Add Link
        </Button>
      )}

      <TextField
        size="small"
        fullWidth
        multiline
        rows={2}
        placeholder="Notes (optional)"
        value={notes}
        onChange={(e) => setNotes(e.target.value)}
        disabled={disabled}
        sx={{ mb: 1 }}
      />

      {!disabled && (
        <Button variant="contained" size="small" onClick={handleSave} disabled={hasErrors}>
          Save Evidence
        </Button>
      )}
    </Box>
  );
}
