// Generated by AI on 05/10/2026
import { Box, LinearProgress, Typography } from '@mui/material';

interface ProgressBarProps {
  completed: number;
  total: number;
}

export default function ProgressBar({ completed, total }: ProgressBarProps) {
  const pct = total > 0 ? Math.round((completed / total) * 100) : 0;
  return (
    <Box sx={{ mb: 2 }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 0.5 }}>
        <Typography variant="body2" color="text.secondary">
          Progress
        </Typography>
        <Typography variant="body2" color="text.secondary">
          {completed} / {total} ({pct}%)
        </Typography>
      </Box>
      <LinearProgress variant="determinate" value={pct} sx={{ height: 10, borderRadius: 5 }} />
    </Box>
  );
}
