// Generated by AI on 05/10/2026
import { Navigate } from 'react-router-dom';
import { useMe } from '../api/participantApi';
import { CircularProgress, Box } from '@mui/material';

interface ProtectedRouteProps {
  children: React.ReactNode;
  requiredRole?: 'admin';
}

export default function ProtectedRoute({ children, requiredRole }: ProtectedRouteProps) {
  const { data: me, isLoading } = useMe();

  if (isLoading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', mt: 10 }}>
        <CircularProgress />
      </Box>
    );
  }

  if (!me) return <Navigate to="/" replace />;
  if (requiredRole === 'admin' && !me.isAdmin) return <Navigate to="/" replace />;

  return <>{children}</>;
}
