// Generated by AI on 05/10/2026
import { Chip } from '@mui/material';
import type { CriterionStatus } from '../types';

const statusConfig: Record<CriterionStatus, { label: string; color: 'default' | 'info' | 'warning' | 'success' | 'error' }> = {
  NotStarted: { label: 'Not Started', color: 'default' },
  InProgress: { label: 'In Progress', color: 'info' },
  EvidenceSubmitted: { label: 'Submitted', color: 'warning' },
  Approved: { label: 'Approved', color: 'success' },
  Rejected: { label: 'Rejected', color: 'error' },
};

interface SubmissionStatusProps {
  status: CriterionStatus;
  feedback?: string | null;
}

export default function SubmissionStatus({ status, feedback }: SubmissionStatusProps) {
  const config = statusConfig[status];
  return (
    <>
      <Chip label={config.label} color={config.color} size="small" />
      {status === 'Rejected' && feedback && (
        <Chip label={feedback} color="error" variant="outlined" size="small" sx={{ ml: 1, maxWidth: 300 }} />
      )}
    </>
  );
}
