// Generated by AI on 05/12/2026
import {
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Box,
  Typography,
  Table,
  TableHead,
  TableRow,
  TableCell,
  TableBody,
  Chip,
  Stack,
} from '@mui/material';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import { useNavigate } from 'react-router-dom';
import type { TeamProgressDto } from '../types';

const levelColors: Record<string, string> = {
  Greenhorn: '#8bc34a',
  Wayfinder: '#2196f3',
  TrailGuide: '#ff9800',
  Pioneer: '#9c27b0',
};

interface TeamCardProps {
  team: TeamProgressDto;
}

export default function TeamCard({ team }: TeamCardProps) {
  const navigate = useNavigate();
  const totalMembers = team.memberCount || 1;

  return (
    <Accordion>
      <AccordionSummary expandIcon={<ExpandMoreIcon />}>
        <Box sx={{ display: 'flex', alignItems: 'center', width: '100%', gap: 2 }}>
          <Typography sx={{ fontWeight: 'bold', minWidth: 160 }}>
            {team.teamName}
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ minWidth: 80 }}>
            {team.memberCount} member{team.memberCount !== 1 ? 's' : ''}
          </Typography>
          <Box sx={{ flexGrow: 1, display: 'flex', height: 16, borderRadius: 1, overflow: 'hidden' }}>
            {Object.entries(levelColors).map(([level, color]) => {
              const count = team.levelCounts[level] || 0;
              if (count === 0) return null;
              const pct = (count / totalMembers) * 100;
              return (
                <Box
                  key={level}
                  sx={{ width: `${pct}%`, backgroundColor: color }}
                  title={`${level}: ${count}`}
                />
              );
            })}
          </Box>
          <Stack direction="row" spacing={0.5} sx={{ minWidth: 200 }}>
            {Object.entries(team.levelCounts).map(([level, count]) =>
              count > 0 ? (
                <Chip
                  key={level}
                  label={`${level[0]}:${count}`}
                  size="small"
                  sx={{ backgroundColor: levelColors[level], color: '#fff', fontSize: '0.7rem' }}
                />
              ) : null
            )}
          </Stack>
        </Box>
      </AccordionSummary>
      <AccordionDetails>
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell>Name</TableCell>
              <TableCell>Level</TableCell>
              <TableCell>Days at Level</TableCell>
              <TableCell>Last Evidence</TableCell>
              <TableCell>Status</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {team.members.map((member) => (
              <TableRow key={member.userId}>
                <TableCell>
                  <Typography
                    component="span"
                    sx={{ cursor: 'pointer', color: 'primary.main', textDecoration: 'underline' }}
                    onClick={() => navigate(`/admin/participant/${member.userId}`)}
                  >
                    {member.displayName}
                  </Typography>
                </TableCell>
                <TableCell>{member.currentLevel}</TableCell>
                <TableCell>{member.daysAtCurrentLevel}</TableCell>
                <TableCell>
                  {member.lastEvidenceDate
                    ? new Date(member.lastEvidenceDate).toLocaleDateString()
                    : '—'}
                </TableCell>
                <TableCell>
                  {member.isStalled ? (
                    <Chip label="Stalled" color="warning" size="small" />
                  ) : (
                    <Chip label="Active" color="success" size="small" />
                  )}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </AccordionDetails>
    </Accordion>
  );
}
