// Generated by AI on 05/10/2026
import {
  List,
  ListItem,
  ListItemText,
  Typography,
} from '@mui/material';
import type { TrainingLink } from '../types';

interface TrainingLinkListProps {
  links: TrainingLink[];
}

export default function TrainingLinkList({ links }: TrainingLinkListProps) {
  const grouped = links.reduce<Record<string, TrainingLink[]>>((acc, link) => {
    if (!acc[link.category]) acc[link.category] = [];
    acc[link.category].push(link);
    return acc;
  }, {});

  return (
    <>
      {Object.entries(grouped).map(([category, items]) => (
        <div key={category}>
          <Typography variant="subtitle2" sx={{ mt: 2, mb: 0.5 }}>
            {category}
          </Typography>
          <List dense>
            {items.map((item) => (
              <ListItem key={item.id} disablePadding>
                <ListItemText
                  primary={
                    <a href={item.url} target="_blank" rel="noopener noreferrer">
                      {item.title}
                    </a>
                  }
                />
              </ListItem>
            ))}
          </List>
        </div>
      ))}
    </>
  );
}
