// Generated by AI on 05/10/2026
import type { ExitCriterion, BadgeLevel } from '../types';

const exitCriteria: ExitCriterion[] = [
  // Greenhorn
  { id: 'greenhorn-1', level: 'Greenhorn', criterionNumber: 1, title: 'Deliver a sample application', description: 'Use GitHub Copilot and Agent OS to deliver a sample application. Push a feature branch with your name in the branch name and submit for review.', evidenceType: 'url' },
  { id: 'greenhorn-2', level: 'Greenhorn', criterionNumber: 2, title: 'Complete AI-First SDLC Training', description: 'Complete the AI-First SDLC Training course.', evidenceType: 'url' },
  { id: 'greenhorn-3', level: 'Greenhorn', criterionNumber: 3, title: 'Deliver 5 stories using Agent Mode', description: 'Provide evidence of completing 5 stories using Agent Mode.', evidenceType: 'multi-url' },

  // Wayfinder
  { id: 'wayfinder-1', level: 'Wayfinder', criterionNumber: 1, title: 'Complete Copilot Training', description: 'Complete Course GH-300T00-A: GitHub Copilot (Microsoft Learn) or a similar alternative training.', evidenceType: 'url' },
  { id: 'wayfinder-2', level: 'Wayfinder', criterionNumber: 2, title: '80% AI-assisted delivery (30+ stories)', description: 'Provide evidence of 80% of stories developed utilizing AI tooling over 3 months, with a minimum of 30 stories completed with AI.', evidenceType: 'multi-url' },
  { id: 'wayfinder-3', level: 'Wayfinder', criterionNumber: 3, title: 'Repository Configuration', description: 'Provide GitHub links to repository agent instructions configuration.', evidenceType: 'multi-url' },
  { id: 'wayfinder-4', level: 'Wayfinder', criterionNumber: 4, title: 'AI Research (3 recordings)', description: 'Provide 3 Webex recordings of using AI to do research on a WO or new Epic.', evidenceType: 'multi-url' },
  { id: 'wayfinder-5', level: 'Wayfinder', criterionNumber: 5, title: 'AI Guild Participation', description: 'Provide evidence of participation in an AI guild.', evidenceType: 'url' },

  // Trail Guide
  { id: 'trailguide-1', level: 'TrailGuide', criterionNumber: 1, title: 'Automate Code Delivery', description: 'Develop an automated code delivery pipeline done by Agents; must include a human in the loop for code review.', evidenceType: 'url' },
  { id: 'trailguide-2', level: 'TrailGuide', criterionNumber: 2, title: 'Multi-Agent Development', description: 'Provide evidence that you are utilizing a Multi-Agent setup locally to deliver epics.', evidenceType: 'url' },
  { id: 'trailguide-3', level: 'TrailGuide', criterionNumber: 3, title: 'Lead a Guild', description: 'Recruit a guild of at least 5 engineers; coach 5 engineers to achieve the Trail Guide badge.', evidenceType: 'multi-url' },
];

export function InMemoryStorage_GetExitCriteria(level: BadgeLevel): ExitCriterion[] {
  return exitCriteria
    .filter((c) => c.level === level)
    .sort((a, b) => a.criterionNumber - b.criterionNumber);
}
