// Generated by AI on 05/10/2026
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.Identity.Web;

namespace AiTrailTracker.Api.Auth;

public static class AzureAdAuthExtensions
{
    public static IServiceCollection AddAzureAdAuth(
        this IServiceCollection services,
        IConfiguration configuration)
    {
        services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddMicrosoftIdentityWebApi(configuration.GetSection("AzureAd"));

        services.AddAuthorization(options =>
        {
            options.AddPolicy("AdminOnly", policy =>
                policy.RequireClaim("roles", "TrailAdmin"));
        });

        return services;
    }
}
