// Generated by AI on 05/10/2026
using System.Security.Claims;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Authentication;
using Microsoft.Extensions.Options;

namespace AiTrailTracker.Api.Auth;

public class DevBypassAuthHandler : AuthenticationHandler<AuthenticationSchemeOptions>
{
    private readonly IConfiguration _configuration;

    public DevBypassAuthHandler(
        IOptionsMonitor<AuthenticationSchemeOptions> options,
        ILoggerFactory logger,
        UrlEncoder encoder,
        IConfiguration configuration)
        : base(options, logger, encoder)
    {
        _configuration = configuration;
    }

    protected override Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        var userId = _configuration["DevAuth:UserId"] ?? "dev-user-001";
        var displayName = _configuration["DevAuth:DisplayName"] ?? "Dev User";
        var email = _configuration["DevAuth:Email"] ?? "devuser@example.com";
        var isAdmin = _configuration.GetValue<bool>("DevAuth:IsAdmin");

        var claims = new List<Claim>
        {
            new(ClaimTypes.NameIdentifier, userId),
            new("oid", userId),
            new(ClaimTypes.Name, displayName),
            new(ClaimTypes.Email, email),
        };

        if (isAdmin)
        {
            claims.Add(new Claim("roles", "TrailAdmin"));
        }

        var identity = new ClaimsIdentity(claims, "DevBypass");
        var principal = new ClaimsPrincipal(identity);
        var ticket = new AuthenticationTicket(principal, "DevBypass");

        return Task.FromResult(AuthenticateResult.Success(ticket));
    }
}
