// Generated by AI on 05/10/2026
// Modified by AI on 05/11/2026. Edit #1.
using Azure.Data.Tables;
using AiTrailTracker.Api.Models;
using System.Text.Json;

namespace AiTrailTracker.Api.Storage;

public class AzureTableStorage : ITrailStorage
{
    private readonly TableClient _participantsTable;
    private readonly TableClient _evidenceTable;
    private readonly TableClient _levelSubmissionsTable;
    private readonly TableClient _trainingLinksTable;
    private readonly TableClient _activityLogsTable;

    public AzureTableStorage(IConfiguration configuration)
    {
        var connectionString = configuration["AzureTableStorage:ConnectionString"]!;
        var serviceClient = new TableServiceClient(connectionString);

        _participantsTable = serviceClient.GetTableClient("Participants");
        _participantsTable.CreateIfNotExists();

        _evidenceTable = serviceClient.GetTableClient("EvidenceSubmissions");
        _evidenceTable.CreateIfNotExists();

        _levelSubmissionsTable = serviceClient.GetTableClient("LevelSubmissions");
        _levelSubmissionsTable.CreateIfNotExists();

        _trainingLinksTable = serviceClient.GetTableClient("TrainingLinks");
        _trainingLinksTable.CreateIfNotExists();

        _activityLogsTable = serviceClient.GetTableClient("ActivityLogs");
        _activityLogsTable.CreateIfNotExists();
    }

    public async Task<Participant?> GetParticipantAsync(string userId)
    {
        try
        {
            var entity = await _participantsTable.GetEntityAsync<TableEntity>("participant", userId);
            return MapToParticipant(entity.Value);
        }
        catch (Azure.RequestFailedException ex) when (ex.Status == 404)
        {
            return null;
        }
    }

    public async Task<List<Participant>> GetAllParticipantsAsync()
    {
        var results = new List<Participant>();
        await foreach (var entity in _participantsTable.QueryAsync<TableEntity>(e => e.PartitionKey == "participant"))
        {
            results.Add(MapToParticipant(entity));
        }
        return results;
    }

    public async Task UpsertParticipantAsync(Participant participant)
    {
        var entity = new TableEntity("participant", participant.UserId)
        {
            { "DisplayName", participant.DisplayName },
            { "Email", participant.Email },
            { "Team", participant.Team },
            { "GuildName", participant.GuildName },
            { "CurrentLevel", (int)participant.CurrentLevel },
            { "IsAdmin", participant.IsAdmin },
            { "CreatedAt", participant.CreatedAt },
            { "LastAdvancementAt", participant.LastAdvancementAt },
        };
        await _participantsTable.UpsertEntityAsync(entity);
    }

    public async Task<EvidenceSubmission?> GetEvidenceAsync(string userId, string criterionId)
    {
        try
        {
            var entity = await _evidenceTable.GetEntityAsync<TableEntity>(userId, criterionId);
            return MapToEvidence(entity.Value);
        }
        catch (Azure.RequestFailedException ex) when (ex.Status == 404)
        {
            return null;
        }
    }

    public async Task<List<EvidenceSubmission>> GetEvidenceByUserAndLevelAsync(string userId, BadgeLevel level)
    {
        var results = new List<EvidenceSubmission>();
        var levelInt = (int)level;
        await foreach (var entity in _evidenceTable.QueryAsync<TableEntity>(
            e => e.PartitionKey == userId && (int)e["Level"] == levelInt))
        {
            results.Add(MapToEvidence(entity));
        }
        return results;
    }

    public async Task UpsertEvidenceAsync(EvidenceSubmission evidence)
    {
        var entity = new TableEntity(evidence.UserId, evidence.CriterionId)
        {
            { "Level", (int)evidence.Level },
            { "EvidenceLinksJson", JsonSerializer.Serialize(evidence.EvidenceLinks) },
            { "Notes", evidence.Notes },
            { "Status", (int)evidence.Status },
            { "AdminFeedback", evidence.AdminFeedback },
            { "SubmittedAt", evidence.SubmittedAt },
            { "ReviewedAt", evidence.ReviewedAt },
            { "ReviewedBy", evidence.ReviewedBy },
        };
        await _evidenceTable.UpsertEntityAsync(entity);
    }

    public async Task<LevelSubmission?> GetLevelSubmissionAsync(string userId, BadgeLevel level)
    {
        try
        {
            var entity = await _levelSubmissionsTable.GetEntityAsync<TableEntity>(userId, level.ToString());
            return MapToLevelSubmission(entity.Value);
        }
        catch (Azure.RequestFailedException ex) when (ex.Status == 404)
        {
            return null;
        }
    }

    public async Task<List<LevelSubmission>> GetPendingSubmissionsAsync()
    {
        var results = new List<LevelSubmission>();
        await foreach (var entity in _levelSubmissionsTable.QueryAsync<TableEntity>(
            e => (bool)e["IsSubmitted"] == true && (bool)e["IsApproved"] == false))
        {
            results.Add(MapToLevelSubmission(entity));
        }
        return results.OrderBy(s => s.SubmittedAt).ToList();
    }

    public async Task<List<LevelSubmission>> GetSubmissionsByUserAsync(string userId)
    {
        var results = new List<LevelSubmission>();
        await foreach (var entity in _levelSubmissionsTable.QueryAsync<TableEntity>(e => e.PartitionKey == userId))
        {
            results.Add(MapToLevelSubmission(entity));
        }
        return results.OrderBy(s => s.Level).ToList();
    }

    public async Task UpsertLevelSubmissionAsync(LevelSubmission submission)
    {
        var entity = new TableEntity(submission.UserId, submission.Level.ToString())
        {
            { "IsSubmitted", submission.IsSubmitted },
            { "SubmittedAt", submission.SubmittedAt },
            { "IsApproved", submission.IsApproved },
            { "ApprovedAt", submission.ApprovedAt },
            { "ApprovedBy", submission.ApprovedBy },
        };
        await _levelSubmissionsTable.UpsertEntityAsync(entity);
    }

    public async Task<List<TrainingLink>> GetTrainingLinksAsync(BadgeLevel level)
    {
        var results = new List<TrainingLink>();
        await foreach (var entity in _trainingLinksTable.QueryAsync<TableEntity>(e => e.PartitionKey == level.ToString()))
        {
            results.Add(new TrainingLink
            {
                Id = entity.RowKey!,
                Level = level,
                Category = entity.GetString("Category") ?? string.Empty,
                Title = entity.GetString("Title") ?? string.Empty,
                Url = entity.GetString("Url") ?? string.Empty,
                SortOrder = entity.GetInt32("SortOrder") ?? 0,
            });
        }
        return results.OrderBy(l => l.SortOrder).ToList();
    }

    private static Participant MapToParticipant(TableEntity entity) => new()
    {
        UserId = entity.RowKey!,
        DisplayName = entity.GetString("DisplayName") ?? string.Empty,
        Email = entity.GetString("Email") ?? string.Empty,
        Team = entity.GetString("Team") ?? string.Empty,
        GuildName = entity.GetString("GuildName") ?? string.Empty,
        CurrentLevel = (BadgeLevel)(entity.GetInt32("CurrentLevel") ?? 1),
        IsAdmin = entity.GetBoolean("IsAdmin") ?? false,
        CreatedAt = entity.GetDateTimeOffset("CreatedAt")?.UtcDateTime ?? DateTime.UtcNow,
        LastAdvancementAt = entity.GetDateTimeOffset("LastAdvancementAt")?.UtcDateTime,
    };

    private static EvidenceSubmission MapToEvidence(TableEntity entity) => new()
    {
        Id = $"{entity.PartitionKey}:{entity.RowKey}",
        UserId = entity.PartitionKey!,
        CriterionId = entity.RowKey!,
        Level = (BadgeLevel)(entity.GetInt32("Level") ?? 1),
        EvidenceLinks = JsonSerializer.Deserialize<List<string>>(entity.GetString("EvidenceLinksJson") ?? "[]") ?? new(),
        Notes = entity.GetString("Notes") ?? string.Empty,
        Status = (CriterionStatus)(entity.GetInt32("Status") ?? 0),
        AdminFeedback = entity.GetString("AdminFeedback"),
        SubmittedAt = entity.GetDateTimeOffset("SubmittedAt")?.UtcDateTime,
        ReviewedAt = entity.GetDateTimeOffset("ReviewedAt")?.UtcDateTime,
        ReviewedBy = entity.GetString("ReviewedBy"),
    };

    private static LevelSubmission MapToLevelSubmission(TableEntity entity) => new()
    {
        Id = $"{entity.PartitionKey}:{entity.RowKey}",
        UserId = entity.PartitionKey!,
        Level = Enum.Parse<BadgeLevel>(entity.RowKey!),
        IsSubmitted = entity.GetBoolean("IsSubmitted") ?? false,
        SubmittedAt = entity.GetDateTimeOffset("SubmittedAt")?.UtcDateTime,
        IsApproved = entity.GetBoolean("IsApproved") ?? false,
        ApprovedAt = entity.GetDateTimeOffset("ApprovedAt")?.UtcDateTime,
        ApprovedBy = entity.GetString("ApprovedBy"),
    };

    // Pioneer Activity Log
    public async Task<List<PioneerActivityLog>> GetActivityLogsAsync(string userId)
    {
        var results = new List<PioneerActivityLog>();
        await foreach (var entity in _activityLogsTable.QueryAsync<TableEntity>(e => e.PartitionKey == userId))
        {
            results.Add(new PioneerActivityLog
            {
                Id = entity.RowKey!,
                UserId = userId,
                Date = entity.GetDateTimeOffset("Date")?.UtcDateTime ?? DateTime.UtcNow,
                Description = entity.GetString("Description") ?? string.Empty,
                Category = entity.GetString("Category") ?? string.Empty,
            });
        }
        return results.OrderByDescending(l => l.Date).ToList();
    }

    public async Task AddActivityLogAsync(PioneerActivityLog log)
    {
        log.Id = Guid.NewGuid().ToString();
        var entity = new TableEntity(log.UserId, log.Id)
        {
            { "Date", log.Date },
            { "Description", log.Description },
            { "Category", log.Category },
        };
        await _activityLogsTable.UpsertEntityAsync(entity);
    }
}
