// Generated by AI on 05/10/2026
// Modified by AI on 05/11/2026. Edit #1.
using System.Collections.Concurrent;
using AiTrailTracker.Api.Models;

namespace AiTrailTracker.Api.Storage;

public class InMemoryStorage : ITrailStorage
{
    private readonly ConcurrentDictionary<string, Participant> _participants = new();
    private readonly ConcurrentDictionary<string, EvidenceSubmission> _evidence = new();
    private readonly ConcurrentDictionary<string, LevelSubmission> _levelSubmissions = new();
    private readonly ConcurrentDictionary<string, TrainingLink> _trainingLinks = new();
    private readonly ConcurrentDictionary<string, PioneerActivityLog> _activityLogs = new();

    public InMemoryStorage()
    {
        SeedTrainingLinks();
    }

    // Participants
    public Task<Participant?> GetParticipantAsync(string userId)
    {
        _participants.TryGetValue(userId, out var participant);
        return Task.FromResult(participant);
    }

    public Task<List<Participant>> GetAllParticipantsAsync()
    {
        return Task.FromResult(_participants.Values.ToList());
    }

    public Task UpsertParticipantAsync(Participant participant)
    {
        _participants[participant.UserId] = participant;
        return Task.CompletedTask;
    }

    // Evidence Submissions
    public Task<EvidenceSubmission?> GetEvidenceAsync(string userId, string criterionId)
    {
        var key = $"{userId}:{criterionId}";
        _evidence.TryGetValue(key, out var evidence);
        return Task.FromResult(evidence);
    }

    public Task<List<EvidenceSubmission>> GetEvidenceByUserAndLevelAsync(string userId, BadgeLevel level)
    {
        var results = _evidence.Values
            .Where(e => e.UserId == userId && e.Level == level)
            .ToList();
        return Task.FromResult(results);
    }

    public Task UpsertEvidenceAsync(EvidenceSubmission evidence)
    {
        var key = $"{evidence.UserId}:{evidence.CriterionId}";
        evidence.Id = key;
        _evidence[key] = evidence;
        return Task.CompletedTask;
    }

    // Level Submissions
    public Task<LevelSubmission?> GetLevelSubmissionAsync(string userId, BadgeLevel level)
    {
        var key = $"{userId}:{level}";
        _levelSubmissions.TryGetValue(key, out var submission);
        return Task.FromResult(submission);
    }

    public Task<List<LevelSubmission>> GetPendingSubmissionsAsync()
    {
        var results = _levelSubmissions.Values
            .Where(s => s.IsSubmitted && !s.IsApproved)
            .OrderBy(s => s.SubmittedAt)
            .ToList();
        return Task.FromResult(results);
    }

    public Task<List<LevelSubmission>> GetSubmissionsByUserAsync(string userId)
    {
        var results = _levelSubmissions.Values
            .Where(s => s.UserId == userId)
            .OrderBy(s => s.Level)
            .ToList();
        return Task.FromResult(results);
    }

    public Task UpsertLevelSubmissionAsync(LevelSubmission submission)
    {
        var key = $"{submission.UserId}:{submission.Level}";
        submission.Id = key;
        _levelSubmissions[key] = submission;
        return Task.CompletedTask;
    }

    // Training Links
    public Task<List<TrainingLink>> GetTrainingLinksAsync(BadgeLevel level)
    {
        var results = _trainingLinks.Values
            .Where(l => l.Level == level)
            .OrderBy(l => l.SortOrder)
            .ToList();
        return Task.FromResult(results);
    }

    private void SeedTrainingLinks()
    {
        var links = new List<TrainingLink>
        {
            new() { Id = "gl-1", Level = BadgeLevel.Greenhorn, Category = "Training Materials", Title = "AI SDLC Interactive Training", Url = "https://paycor-ai-sdlc-training-a9azfbfff5ctbnd9.northcentralus-01.azurewebsites.net/", SortOrder = 1 },
            new() { Id = "gl-2", Level = BadgeLevel.Greenhorn, Category = "Training Materials", Title = "AI SDLC Documentation", Url = "https://paychex.sharepoint.com/:u:/s/pycr_EnterpriseArchitectureTeam/IQBwfNswA2IcRZ26PLm9iFzXAaND2gGQSvylWw-lghhG-UU?e=Yk9FjR", SortOrder = 2 },
            new() { Id = "gl-3", Level = BadgeLevel.Greenhorn, Category = "Environment Setup", Title = "Enhanced Context Setup", Url = "https://paychex.sharepoint.com/:u:/s/pycr_EnterpriseArchitectureTeam/IQCse9s7GXigTpF1UUPXdB8iAQSmAgcLcO7VAxzFZvJuOWQ?e=FQkRcP", SortOrder = 3 },
            new() { Id = "gl-4", Level = BadgeLevel.Greenhorn, Category = "Environment Setup", Title = "Multi-repo Workspaces", Url = "https://paychex.sharepoint.com/:u:/s/pycr_EnterpriseArchitectureTeam/IQCHFDD09Ha9S6tZyH6C-YaAAWwzfD9i1v91eR1gq6kyew4?e=ijzgoN", SortOrder = 4 },
            new() { Id = "gl-5", Level = BadgeLevel.Greenhorn, Category = "Environment Setup", Title = "AI Attribution and Tagging", Url = "https://paychex.sharepoint.com/:u:/s/pycr_EnterpriseArchitectureTeam/IQDU4oyDOSbgQrf55PQ5PXjVAX85lzefNB7JOdOHSwO48A0?e=C7rtZg", SortOrder = 5 },
            new() { Id = "gl-6", Level = BadgeLevel.Greenhorn, Category = "Quality Control", Title = "Using AI for Code Reviews — ADO", Url = "https://github.com/PaycorInc/Paycor.PR.Reviewer?tab=readme-ov-file#how-to-add-a-custom-prompt", SortOrder = 6 },
            new() { Id = "gl-7", Level = BadgeLevel.Greenhorn, Category = "Quality Control", Title = "Using AI for Code Review — GitHub", Url = "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/request-a-code-review/use-code-review", SortOrder = 7 },
            new() { Id = "gl-8", Level = BadgeLevel.Greenhorn, Category = "Quality Control", Title = "Using AI for Local Code Review", Url = "https://docs.github.com/en/copilot/how-tos/use-copilot-agents/request-a-code-review/use-code-review?tool=vscode", SortOrder = 8 },
        };

        foreach (var link in links)
        {
            _trainingLinks[link.Id] = link;
        }
    }

    private static readonly List<ExitCriterion> _exitCriteria = new()
    {
        // Greenhorn
        new() { Id = "greenhorn-1", Level = BadgeLevel.Greenhorn, CriterionNumber = 1, Title = "Deliver a sample application", Description = "Use GitHub Copilot and Agent OS to deliver a sample application. Push a feature branch with your name in the branch name and submit for review.", EvidenceType = "url" },
        new() { Id = "greenhorn-2", Level = BadgeLevel.Greenhorn, CriterionNumber = 2, Title = "Complete AI-First SDLC Training", Description = "Complete the AI-First SDLC Training course.", EvidenceType = "url" },
        new() { Id = "greenhorn-3", Level = BadgeLevel.Greenhorn, CriterionNumber = 3, Title = "Deliver 5 stories using Agent Mode", Description = "Provide evidence of completing 5 stories using Agent Mode.", EvidenceType = "multi-url" },

        // Wayfinder
        new() { Id = "wayfinder-1", Level = BadgeLevel.Wayfinder, CriterionNumber = 1, Title = "Complete Copilot Training", Description = "Complete Course GH-300T00-A: GitHub Copilot (Microsoft Learn) or a similar alternative training.", EvidenceType = "url" },
        new() { Id = "wayfinder-2", Level = BadgeLevel.Wayfinder, CriterionNumber = 2, Title = "80% AI-assisted delivery (30+ stories)", Description = "Provide evidence of 80% of stories developed utilizing AI tooling over 3 months, with a minimum of 30 stories completed with AI.", EvidenceType = "multi-url" },
        new() { Id = "wayfinder-3", Level = BadgeLevel.Wayfinder, CriterionNumber = 3, Title = "Repository Configuration", Description = "Provide GitHub links to repository agent instructions configuration.", EvidenceType = "multi-url" },
        new() { Id = "wayfinder-4", Level = BadgeLevel.Wayfinder, CriterionNumber = 4, Title = "AI Research (3 recordings)", Description = "Provide 3 Webex recordings of using AI to do research on a WO or new Epic.", EvidenceType = "multi-url" },
        new() { Id = "wayfinder-5", Level = BadgeLevel.Wayfinder, CriterionNumber = 5, Title = "AI Guild Participation", Description = "Provide evidence of participation in an AI guild.", EvidenceType = "url" },

        // Trail Guide
        new() { Id = "trailguide-1", Level = BadgeLevel.TrailGuide, CriterionNumber = 1, Title = "Automate Code Delivery", Description = "Develop an automated code delivery pipeline done by Agents; must include a human in the loop for code review.", EvidenceType = "url" },
        new() { Id = "trailguide-2", Level = BadgeLevel.TrailGuide, CriterionNumber = 2, Title = "Multi-Agent Development", Description = "Provide evidence that you are utilizing a Multi-Agent setup locally to deliver epics.", EvidenceType = "url" },
        new() { Id = "trailguide-3", Level = BadgeLevel.TrailGuide, CriterionNumber = 3, Title = "Lead a Guild", Description = "Recruit a guild of at least 5 engineers; coach 5 engineers to achieve the Trail Guide badge.", EvidenceType = "multi-url" },
    };

    public static List<ExitCriterion> GetExitCriteria(BadgeLevel level)
    {
        return _exitCriteria.Where(c => c.Level == level).OrderBy(c => c.CriterionNumber).ToList();
    }

    public static List<ExitCriterion> GetAllExitCriteria()
    {
        return _exitCriteria;
    }

    // Pioneer Activity Log
    public Task<List<PioneerActivityLog>> GetActivityLogsAsync(string userId)
    {
        var results = _activityLogs.Values
            .Where(l => l.UserId == userId)
            .OrderByDescending(l => l.Date)
            .ToList();
        return Task.FromResult(results);
    }

    public Task AddActivityLogAsync(PioneerActivityLog log)
    {
        log.Id = Guid.NewGuid().ToString();
        _activityLogs[log.Id] = log;
        return Task.CompletedTask;
    }
}
