// Generated by AI on 05/10/2026
// Modified by AI on 05/11/2026. Edit #1.
using AiTrailTracker.Api.Models;

namespace AiTrailTracker.Api.Storage;

public interface ITrailStorage
{
    // Participants
    Task<Participant?> GetParticipantAsync(string userId);
    Task<List<Participant>> GetAllParticipantsAsync();
    Task UpsertParticipantAsync(Participant participant);

    // Evidence Submissions
    Task<EvidenceSubmission?> GetEvidenceAsync(string userId, string criterionId);
    Task<List<EvidenceSubmission>> GetEvidenceByUserAndLevelAsync(string userId, BadgeLevel level);
    Task UpsertEvidenceAsync(EvidenceSubmission evidence);

    // Level Submissions
    Task<LevelSubmission?> GetLevelSubmissionAsync(string userId, BadgeLevel level);
    Task<List<LevelSubmission>> GetPendingSubmissionsAsync();
    Task<List<LevelSubmission>> GetSubmissionsByUserAsync(string userId);
    Task UpsertLevelSubmissionAsync(LevelSubmission submission);

    // Training Links
    Task<List<TrainingLink>> GetTrainingLinksAsync(BadgeLevel level);

    // Pioneer Activity Log
    Task<List<PioneerActivityLog>> GetActivityLogsAsync(string userId);
    Task AddActivityLogAsync(PioneerActivityLog log);
}
