// Generated by AI on 05/11/2026
using System.Text.RegularExpressions;

namespace AiTrailTracker.Api.Validation;

public static partial class InputSanitizer
{
    public static string SanitizeText(string? input)
    {
        if (string.IsNullOrEmpty(input)) return string.Empty;

        // Strip HTML tags
        var result = HtmlTagRegex().Replace(input, string.Empty);
        // Remove event handler attributes that may sneak in without full tags
        result = EventHandlerRegex().Replace(result, string.Empty);
        return result.Trim();
    }

    [GeneratedRegex(@"<[^>]*>", RegexOptions.Compiled)]
    private static partial Regex HtmlTagRegex();

    [GeneratedRegex(@"on\w+\s*=", RegexOptions.IgnoreCase | RegexOptions.Compiled)]
    private static partial Regex EventHandlerRegex();
}
