// Generated by AI on 05/11/2026
namespace AiTrailTracker.Api.Validation;

public static class UrlValidator
{
    private static readonly HashSet<string> AllowedSchemes = new(StringComparer.OrdinalIgnoreCase) { "http", "https" };

    public static bool IsValidUrl(string url)
    {
        if (string.IsNullOrWhiteSpace(url)) return false;
        if (!Uri.TryCreate(url, UriKind.Absolute, out var uri)) return false;
        return AllowedSchemes.Contains(uri.Scheme);
    }

    public static List<string> ValidateEvidenceLinks(List<string> links)
    {
        var errors = new List<string>();
        for (int i = 0; i < links.Count; i++)
        {
            if (!IsValidUrl(links[i]))
            {
                errors.Add($"Evidence link {i + 1} is not a valid URL. Only http:// and https:// URLs are accepted.");
            }
        }
        return errors;
    }
}
