// Generated by AI on 05/11/2026
using AiTrailTracker.Api.Models;
using AiTrailTracker.Api.Services;
using AiTrailTracker.Api.Storage;

namespace AiTrailTracker.Api.Tests;

public class AdminWorkflowTests
{
    private static async Task<(ParticipantService participantSvc, AdminService adminSvc, InMemoryStorage storage)> SetupSubmittedParticipant()
    {
        var storage = new InMemoryStorage();
        var participantSvc = new ParticipantService(storage);
        var adminSvc = new AdminService(storage);

        await participantSvc.GetOrCreateParticipantAsync("user-1", "Test User", "test@example.com");

        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);
        foreach (var c in criteria)
        {
            await participantSvc.SaveEvidenceAsync("user-1", c.Id,
                new List<string> { "https://github.com/org/repo" }, "evidence notes");
        }

        await participantSvc.SubmitLevelForReviewAsync("user-1");
        return (participantSvc, adminSvc, storage);
    }

    // Task 6: Resubmission workflow
    [Fact]
    public async Task RejectEvidence_RequiresFeedback()
    {
        var (_, adminSvc, _) = await SetupSubmittedParticipant();
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        var ex = await Assert.ThrowsAsync<ArgumentException>(
            () => adminSvc.RejectEvidenceAsync("user-1", criteria[0].Id, "admin-1", ""));
        Assert.Contains("Feedback is required", ex.Message);
    }

    [Fact]
    public async Task RejectEvidence_WithFeedback_SetsRejectedStatus()
    {
        var (_, adminSvc, storage) = await SetupSubmittedParticipant();
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);
        var criterionId = criteria[0].Id;

        await adminSvc.RejectEvidenceAsync("user-1", criterionId, "admin-1", "Missing branch name");

        var evidence = await storage.GetEvidenceAsync("user-1", criterionId);
        Assert.Equal(CriterionStatus.Rejected, evidence!.Status);
        Assert.Equal("Missing branch name", evidence.AdminFeedback);
        Assert.Equal("admin-1", evidence.ReviewedBy);
    }

    [Fact]
    public async Task Resubmission_RejectedCriterion_CanBeEdited()
    {
        var (participantSvc, adminSvc, storage) = await SetupSubmittedParticipant();
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);
        var criterionId = criteria[0].Id;

        // Admin rejects
        await adminSvc.RejectEvidenceAsync("user-1", criterionId, "admin-1", "Wrong link");

        // User edits the rejected criterion
        await participantSvc.SaveEvidenceAsync("user-1", criterionId,
            new List<string> { "https://github.com/org/correct-repo" }, "fixed");

        var evidence = await storage.GetEvidenceAsync("user-1", criterionId);
        Assert.Equal(CriterionStatus.InProgress, evidence!.Status);
        Assert.Equal("https://github.com/org/correct-repo", evidence.EvidenceLinks[0]);
    }

    // Task 7: Rejection feedback
    [Fact]
    public async Task RejectEvidence_NullFeedback_Throws()
    {
        var (_, adminSvc, _) = await SetupSubmittedParticipant();
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        var ex = await Assert.ThrowsAsync<ArgumentException>(
            () => adminSvc.RejectEvidenceAsync("user-1", criteria[0].Id, "admin-1", null!));
        Assert.Contains("Feedback is required", ex.Message);
    }

    [Fact]
    public async Task RejectEvidence_WhitespaceFeedback_Throws()
    {
        var (_, adminSvc, _) = await SetupSubmittedParticipant();
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        var ex = await Assert.ThrowsAsync<ArgumentException>(
            () => adminSvc.RejectEvidenceAsync("user-1", criteria[0].Id, "admin-1", "   "));
        Assert.Contains("Feedback is required", ex.Message);
    }

    // Task 8: Level advancement
    [Fact]
    public async Task AdvanceParticipant_AllApproved_Succeeds()
    {
        var (_, adminSvc, storage) = await SetupSubmittedParticipant();
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        // Approve all criteria
        foreach (var c in criteria)
        {
            await adminSvc.ApproveEvidenceAsync("user-1", c.Id, "admin-1");
        }

        await adminSvc.AdvanceParticipantAsync("user-1", "admin-1");

        var participant = await storage.GetParticipantAsync("user-1");
        Assert.Equal(BadgeLevel.Wayfinder, participant!.CurrentLevel);
        Assert.NotNull(participant.LastAdvancementAt);
    }

    [Fact]
    public async Task AdvanceParticipant_NotAllApproved_Throws()
    {
        var (_, adminSvc, _) = await SetupSubmittedParticipant();
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        // Approve only the first criterion
        await adminSvc.ApproveEvidenceAsync("user-1", criteria[0].Id, "admin-1");

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => adminSvc.AdvanceParticipantAsync("user-1", "admin-1"));
        Assert.Contains("not yet approved", ex.Message);
    }

    [Fact]
    public async Task AdvanceParticipant_Pioneer_Throws()
    {
        var storage = new InMemoryStorage();
        var adminSvc = new AdminService(storage);

        // Create a Pioneer participant directly
        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "pioneer-1",
            DisplayName = "Pioneer User",
            Email = "pioneer@example.com",
            CurrentLevel = BadgeLevel.Pioneer,
            CreatedAt = DateTime.UtcNow,
        });

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => adminSvc.AdvanceParticipantAsync("pioneer-1", "admin-1"));
        Assert.Contains("highest level", ex.Message);
    }

    [Fact]
    public async Task AdvanceParticipant_RetainsHistoricalEvidence()
    {
        var (_, adminSvc, storage) = await SetupSubmittedParticipant();
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        foreach (var c in criteria)
        {
            await adminSvc.ApproveEvidenceAsync("user-1", c.Id, "admin-1");
        }

        await adminSvc.AdvanceParticipantAsync("user-1", "admin-1");

        // Evidence for Greenhorn should still exist
        var oldEvidence = await storage.GetEvidenceByUserAndLevelAsync("user-1", BadgeLevel.Greenhorn);
        Assert.NotEmpty(oldEvidence);
        Assert.All(oldEvidence, e => Assert.Equal(CriterionStatus.Approved, e.Status));
    }

    [Fact]
    public async Task ApproveEvidence_SetsApprovedStatus()
    {
        var (_, adminSvc, storage) = await SetupSubmittedParticipant();
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        await adminSvc.ApproveEvidenceAsync("user-1", criteria[0].Id, "admin-1");

        var evidence = await storage.GetEvidenceAsync("user-1", criteria[0].Id);
        Assert.Equal(CriterionStatus.Approved, evidence!.Status);
        Assert.Equal("admin-1", evidence.ReviewedBy);
        Assert.NotNull(evidence.ReviewedAt);
    }
}
