// Generated by AI on 05/11/2026
using AiTrailTracker.Api.Models;
using AiTrailTracker.Api.Storage;

namespace AiTrailTracker.Api.Tests;

public class InMemoryStorageTests
{
    [Fact]
    public async Task Participant_CRUD()
    {
        var storage = new InMemoryStorage();

        // Create
        var participant = new Participant
        {
            UserId = "test-1",
            DisplayName = "Test User",
            Email = "test@example.com",
            CurrentLevel = BadgeLevel.Greenhorn,
            CreatedAt = DateTime.UtcNow,
        };
        await storage.UpsertParticipantAsync(participant);

        // Read
        var retrieved = await storage.GetParticipantAsync("test-1");
        Assert.NotNull(retrieved);
        Assert.Equal("Test User", retrieved.DisplayName);

        // Update
        retrieved.CurrentLevel = BadgeLevel.Wayfinder;
        await storage.UpsertParticipantAsync(retrieved);
        var updated = await storage.GetParticipantAsync("test-1");
        Assert.Equal(BadgeLevel.Wayfinder, updated!.CurrentLevel);
    }

    [Fact]
    public async Task Evidence_CRUD()
    {
        var storage = new InMemoryStorage();

        var evidence = new EvidenceSubmission
        {
            UserId = "user-1",
            CriterionId = "greenhorn-1",
            Level = BadgeLevel.Greenhorn,
            EvidenceLinks = new List<string> { "https://github.com/test" },
            Notes = "Test notes",
            Status = CriterionStatus.InProgress,
        };
        await storage.UpsertEvidenceAsync(evidence);

        // Read
        var retrieved = await storage.GetEvidenceAsync("user-1", "greenhorn-1");
        Assert.NotNull(retrieved);
        Assert.Equal("https://github.com/test", retrieved.EvidenceLinks[0]);

        // List by user and level
        var list = await storage.GetEvidenceByUserAndLevelAsync("user-1", BadgeLevel.Greenhorn);
        Assert.Single(list);

        // Update
        retrieved.Status = CriterionStatus.Approved;
        await storage.UpsertEvidenceAsync(retrieved);
        var updated = await storage.GetEvidenceAsync("user-1", "greenhorn-1");
        Assert.Equal(CriterionStatus.Approved, updated!.Status);
    }

    [Fact]
    public async Task LevelSubmission_CRUD()
    {
        var storage = new InMemoryStorage();

        var submission = new LevelSubmission
        {
            UserId = "user-1",
            Level = BadgeLevel.Greenhorn,
            IsSubmitted = true,
            SubmittedAt = DateTime.UtcNow,
        };
        await storage.UpsertLevelSubmissionAsync(submission);

        var retrieved = await storage.GetLevelSubmissionAsync("user-1", BadgeLevel.Greenhorn);
        Assert.NotNull(retrieved);
        Assert.True(retrieved.IsSubmitted);

        // Pending
        var pending = await storage.GetPendingSubmissionsAsync();
        Assert.Single(pending);
    }

    [Fact]
    public async Task TrainingLinks_ReturnsByLevel()
    {
        var storage = new InMemoryStorage();

        var links = await storage.GetTrainingLinksAsync(BadgeLevel.Greenhorn);
        Assert.NotEmpty(links);
        Assert.All(links, l => Assert.Equal(BadgeLevel.Greenhorn, l.Level));
    }

    [Fact]
    public void GetExitCriteria_ReturnsCorrectLevel()
    {
        var greenhorn = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);
        Assert.Equal(3, greenhorn.Count);

        var wayfinder = InMemoryStorage.GetExitCriteria(BadgeLevel.Wayfinder);
        Assert.Equal(5, wayfinder.Count);

        var trailGuide = InMemoryStorage.GetExitCriteria(BadgeLevel.TrailGuide);
        Assert.Equal(3, trailGuide.Count);

        var pioneer = InMemoryStorage.GetExitCriteria(BadgeLevel.Pioneer);
        Assert.Empty(pioneer); // Pioneer has no exit criteria
    }

    [Fact]
    public async Task GetParticipant_NotFound_ReturnsNull()
    {
        var storage = new InMemoryStorage();
        var result = await storage.GetParticipantAsync("nonexistent");
        Assert.Null(result);
    }
}
