// Generated by AI on 05/11/2026
using AiTrailTracker.Api.Validation;

namespace AiTrailTracker.Api.Tests;

public class InputSanitizerTests
{
    [Theory]
    [InlineData("Plain text notes", "Plain text notes")]
    [InlineData("", "")]
    [InlineData(null, "")]
    public void SanitizeText_PlainText_PassesThrough(string? input, string expected)
    {
        var result = InputSanitizer.SanitizeText(input);
        Assert.Equal(expected, result);
    }

    [Fact]
    public void SanitizeText_AngleBrackets_StripsAsHtml()
    {
        // Angle brackets are stripped because they look like HTML tags
        var result = InputSanitizer.SanitizeText("Notes with special chars: &, <, >");
        Assert.Equal("Notes with special chars: &,", result);
    }

    [Theory]
    [InlineData("<script>alert('xss')</script>", "alert('xss')")]
    [InlineData("<img src=x onerror=alert(1)>", "")]
    [InlineData("Hello <b>world</b>", "Hello world")]
    [InlineData("<div onclick='evil()'>text</div>", "text")]
    public void SanitizeText_XssPayloads_StripsHtml(string input, string expected)
    {
        var result = InputSanitizer.SanitizeText(input);
        Assert.Equal(expected, result);
    }

    [Fact]
    public void SanitizeText_EncodedVariants_Stripped()
    {
        // Basic HTML entities in tags are still stripped
        var result = InputSanitizer.SanitizeText("<script>document.cookie</script>");
        Assert.DoesNotContain("<script>", result);
        Assert.DoesNotContain("</script>", result);
    }
}
