// Generated by AI on 05/12/2026
using AiTrailTracker.Api.Models;
using AiTrailTracker.Api.Services;
using AiTrailTracker.Api.Storage;

namespace AiTrailTracker.Api.Tests;

/// <summary>
/// Reverse-prompted tests: generated by reading ParticipantService implementation
/// and covering all branches and edge cases not already tested elsewhere.
/// </summary>
public class ParticipantServiceTests
{
    #region GetOrCreateParticipantAsync

    [Fact]
    public async Task GetOrCreateParticipant_NewUser_CreatesWithGreenhornLevel()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        var participant = await service.GetOrCreateParticipantAsync("new-user", "Jane Doe", "jane@example.com");

        Assert.Equal("new-user", participant.UserId);
        Assert.Equal("Jane Doe", participant.DisplayName);
        Assert.Equal("jane@example.com", participant.Email);
        Assert.Equal(BadgeLevel.Greenhorn, participant.CurrentLevel);
    }

    [Fact]
    public async Task GetOrCreateParticipant_ExistingUser_ReturnsWithoutOverwriting()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        var first = await service.GetOrCreateParticipantAsync("user-1", "Original Name", "original@example.com");
        var second = await service.GetOrCreateParticipantAsync("user-1", "New Name", "new@example.com");

        // Should return the original, not create a new one
        Assert.Equal("Original Name", second.DisplayName);
        Assert.Equal("original@example.com", second.Email);
    }

    #endregion

    #region GetEvidenceForCurrentLevelAsync

    [Fact]
    public async Task GetEvidenceForCurrentLevel_NonExistentUser_ReturnsEmptyList()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        var result = await service.GetEvidenceForCurrentLevelAsync("nonexistent");

        Assert.Empty(result);
    }

    [Fact]
    public async Task GetEvidenceForCurrentLevel_ExistingUser_ReturnsLevelEvidence()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        await service.GetOrCreateParticipantAsync("user-1", "Test User", "test@example.com");
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);
        await service.SaveEvidenceAsync("user-1", criteria[0].Id,
            new List<string> { "https://github.com/org/repo" }, "notes");

        var result = await service.GetEvidenceForCurrentLevelAsync("user-1");

        Assert.Single(result);
        Assert.Equal(criteria[0].Id, result[0].CriterionId);
    }

    #endregion

    #region SaveEvidenceAsync

    [Fact]
    public async Task SaveEvidence_ParticipantNotFound_Throws()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => service.SaveEvidenceAsync("nonexistent", "criterion-1",
                new List<string> { "https://github.com/test" }, "notes"));
        Assert.Contains("Participant not found", ex.Message);
    }

    [Fact]
    public async Task SaveEvidence_CriterionNotInCurrentLevel_Throws()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        await service.GetOrCreateParticipantAsync("user-1", "Test User", "test@example.com");

        // Use a criterion ID that doesn't belong to Greenhorn
        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => service.SaveEvidenceAsync("user-1", "wayfinder-1",
                new List<string> { "https://github.com/test" }, "notes"));
        Assert.Contains("does not belong to current level", ex.Message);
    }

    [Fact]
    public async Task SaveEvidence_FirstSubmission_CreatesNewRecord()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        await service.GetOrCreateParticipantAsync("user-1", "Test User", "test@example.com");
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        await service.SaveEvidenceAsync("user-1", criteria[0].Id,
            new List<string> { "https://github.com/org/repo" }, "my notes");

        var evidence = await storage.GetEvidenceAsync("user-1", criteria[0].Id);
        Assert.NotNull(evidence);
        Assert.Equal(CriterionStatus.InProgress, evidence!.Status);
        Assert.Equal("my notes", evidence.Notes);
        Assert.Single(evidence.EvidenceLinks);
        Assert.Equal(BadgeLevel.Greenhorn, evidence.Level);
    }

    [Fact]
    public async Task SaveEvidence_UpdateBeforeSubmission_OverwritesPrevious()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        await service.GetOrCreateParticipantAsync("user-1", "Test User", "test@example.com");
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        await service.SaveEvidenceAsync("user-1", criteria[0].Id,
            new List<string> { "https://github.com/original" }, "first attempt");
        await service.SaveEvidenceAsync("user-1", criteria[0].Id,
            new List<string> { "https://github.com/updated" }, "second attempt");

        var evidence = await storage.GetEvidenceAsync("user-1", criteria[0].Id);
        Assert.Equal("https://github.com/updated", evidence!.EvidenceLinks[0]);
        Assert.Equal("second attempt", evidence.Notes);
    }

    [Fact]
    public async Task SaveEvidence_ClearsAdminFeedbackOnResubmit()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        await service.GetOrCreateParticipantAsync("user-1", "Test User", "test@example.com");
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        // Save, submit, reject, then re-save
        foreach (var c in criteria)
        {
            await service.SaveEvidenceAsync("user-1", c.Id,
                new List<string> { "https://github.com/org/repo" }, "notes");
        }
        await service.SubmitLevelForReviewAsync("user-1");

        // Simulate rejection with feedback
        var evidence = await storage.GetEvidenceAsync("user-1", criteria[0].Id);
        evidence!.Status = CriterionStatus.Rejected;
        evidence.AdminFeedback = "Needs more detail";
        await storage.UpsertEvidenceAsync(evidence);

        // Re-save should clear admin feedback
        await service.SaveEvidenceAsync("user-1", criteria[0].Id,
            new List<string> { "https://github.com/fixed" }, "improved notes");

        var updated = await storage.GetEvidenceAsync("user-1", criteria[0].Id);
        Assert.Null(updated!.AdminFeedback);
        Assert.Equal(CriterionStatus.InProgress, updated.Status);
    }

    [Fact]
    public async Task SaveEvidence_NullNotes_SavesEmptyString()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        await service.GetOrCreateParticipantAsync("user-1", "Test User", "test@example.com");
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        await service.SaveEvidenceAsync("user-1", criteria[0].Id,
            new List<string> { "https://github.com/test" }, null);

        var evidence = await storage.GetEvidenceAsync("user-1", criteria[0].Id);
        Assert.Equal(string.Empty, evidence!.Notes);
    }

    #endregion

    #region SubmitLevelForReviewAsync

    [Fact]
    public async Task SubmitLevel_ParticipantNotFound_Throws()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => service.SubmitLevelForReviewAsync("nonexistent"));
        Assert.Contains("Participant not found", ex.Message);
    }

    [Fact]
    public async Task SubmitLevel_PioneerLevel_CannotSubmit()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "pioneer-1",
            DisplayName = "Pioneer User",
            Email = "pioneer@example.com",
            CurrentLevel = BadgeLevel.Pioneer,
            CreatedAt = DateTime.UtcNow,
        });

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => service.SubmitLevelForReviewAsync("pioneer-1"));
        Assert.Contains("highest level", ex.Message);
    }

    [Fact]
    public async Task SubmitLevel_AlreadyApprovedEvidence_StaysApproved()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        await service.GetOrCreateParticipantAsync("user-1", "Test User", "test@example.com");
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        // Save evidence for all criteria
        foreach (var c in criteria)
        {
            await service.SaveEvidenceAsync("user-1", c.Id,
                new List<string> { "https://github.com/org/repo" }, "notes");
        }

        // Manually approve the first criterion before submission
        var first = await storage.GetEvidenceAsync("user-1", criteria[0].Id);
        first!.Status = CriterionStatus.Approved;
        await storage.UpsertEvidenceAsync(first);

        await service.SubmitLevelForReviewAsync("user-1");

        // Approved evidence should remain approved, not reset to EvidenceSubmitted
        var afterSubmit = await storage.GetEvidenceAsync("user-1", criteria[0].Id);
        Assert.Equal(CriterionStatus.Approved, afterSubmit!.Status);

        // Other evidence should be EvidenceSubmitted
        for (int i = 1; i < criteria.Count; i++)
        {
            var e = await storage.GetEvidenceAsync("user-1", criteria[i].Id);
            Assert.Equal(CriterionStatus.EvidenceSubmitted, e!.Status);
        }
    }

    [Fact]
    public async Task SubmitLevel_SetsSubmittedAtTimestamp()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        await service.GetOrCreateParticipantAsync("user-1", "Test User", "test@example.com");
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        foreach (var c in criteria)
        {
            await service.SaveEvidenceAsync("user-1", c.Id,
                new List<string> { "https://github.com/org/repo" }, "notes");
        }

        await service.SubmitLevelForReviewAsync("user-1");

        var evidence = await service.GetEvidenceForCurrentLevelAsync("user-1");
        Assert.All(evidence, e => Assert.NotNull(e.SubmittedAt));
    }

    [Fact]
    public async Task SubmitLevel_CreatesLevelSubmissionRecord()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        await service.GetOrCreateParticipantAsync("user-1", "Test User", "test@example.com");
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        foreach (var c in criteria)
        {
            await service.SaveEvidenceAsync("user-1", c.Id,
                new List<string> { "https://github.com/org/repo" }, "notes");
        }

        await service.SubmitLevelForReviewAsync("user-1");

        var levelSubmission = await storage.GetLevelSubmissionAsync("user-1", BadgeLevel.Greenhorn);
        Assert.NotNull(levelSubmission);
        Assert.True(levelSubmission!.IsSubmitted);
        Assert.NotNull(levelSubmission.SubmittedAt);
    }

    [Fact]
    public async Task SubmitLevel_EvidenceWithEmptyLinks_Throws()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        await service.GetOrCreateParticipantAsync("user-1", "Test User", "test@example.com");
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        // Save evidence with empty links for the first criterion
        await storage.UpsertEvidenceAsync(new EvidenceSubmission
        {
            UserId = "user-1",
            CriterionId = criteria[0].Id,
            Level = BadgeLevel.Greenhorn,
            EvidenceLinks = new List<string>(),
        });

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => service.SubmitLevelForReviewAsync("user-1"));
        Assert.Contains("Missing evidence", ex.Message);
    }

    #endregion

    #region AddActivityLogAsync

    [Fact]
    public async Task AddActivityLog_ParticipantNotFound_Throws()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => service.AddActivityLogAsync("nonexistent", "Activity", "General"));
        Assert.Contains("Participant not found", ex.Message);
    }

    #endregion

    #region GetLevelHistoryAsync

    [Fact]
    public async Task GetLevelHistory_NoSubmissions_ReturnsEmptyList()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        var result = await service.GetLevelHistoryAsync("user-1");

        Assert.Empty(result);
    }

    [Fact]
    public async Task GetLevelHistory_AfterSubmission_IncludesRecord()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        await service.GetOrCreateParticipantAsync("user-1", "Test User", "test@example.com");
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        foreach (var c in criteria)
        {
            await service.SaveEvidenceAsync("user-1", c.Id,
                new List<string> { "https://github.com/org/repo" }, "notes");
        }

        await service.SubmitLevelForReviewAsync("user-1");

        var history = await service.GetLevelHistoryAsync("user-1");
        Assert.Single(history);
        Assert.Equal(BadgeLevel.Greenhorn, history[0].Level);
        Assert.True(history[0].IsSubmitted);
    }

    #endregion
}
