// Generated by AI on 05/11/2026
using AiTrailTracker.Api.Models;
using AiTrailTracker.Api.Services;
using AiTrailTracker.Api.Storage;

namespace AiTrailTracker.Api.Tests;

public class PioneerActivityLogTests
{
    [Fact]
    public async Task AddActivityLog_Pioneer_Succeeds()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "pioneer-1",
            DisplayName = "Pioneer User",
            Email = "pioneer@example.com",
            CurrentLevel = BadgeLevel.Pioneer,
            CreatedAt = DateTime.UtcNow,
        });

        await service.AddActivityLogAsync("pioneer-1", "Published article on AI testing", "Articles");

        var logs = await service.GetActivityLogsAsync("pioneer-1");
        Assert.Single(logs);
        Assert.Equal("Published article on AI testing", logs[0].Description);
        Assert.Equal("Articles", logs[0].Category);
    }

    [Fact]
    public async Task AddActivityLog_NonPioneer_Throws()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        await service.GetOrCreateParticipantAsync("user-1", "Test User", "test@example.com");

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => service.AddActivityLogAsync("user-1", "Some activity", "General"));
        Assert.Contains("only available for Pioneers", ex.Message);
    }

    [Fact]
    public async Task GetActivityLogs_ReturnsOrderedByDate()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "pioneer-1",
            DisplayName = "Pioneer User",
            Email = "pioneer@example.com",
            CurrentLevel = BadgeLevel.Pioneer,
            CreatedAt = DateTime.UtcNow,
        });

        await service.AddActivityLogAsync("pioneer-1", "First activity", "General");
        await service.AddActivityLogAsync("pioneer-1", "Second activity", "Articles");

        var logs = await service.GetActivityLogsAsync("pioneer-1");
        Assert.Equal(2, logs.Count);
        // Most recent first
        Assert.Equal("Second activity", logs[0].Description);
    }
}
