// Generated by AI on 05/11/2026
using AiTrailTracker.Api.Models;
using AiTrailTracker.Api.Services;
using AiTrailTracker.Api.Storage;

namespace AiTrailTracker.Api.Tests;

public class ProgramStatsTests
{
    [Fact]
    public async Task GetProgramStats_EmptyStorage_ReturnsZeros()
    {
        var storage = new InMemoryStorage();
        var adminSvc = new AdminService(storage);

        var stats = await adminSvc.GetProgramStatsAsync();
        Assert.Equal(0, stats.TotalParticipants);
        Assert.Equal(0.0, stats.WayfinderPercentage);
        Assert.Equal(0, stats.PendingReviews);
    }

    [Fact]
    public async Task GetProgramStats_MultipleLevels_CalculatesCorrectly()
    {
        var storage = new InMemoryStorage();
        var adminSvc = new AdminService(storage);

        await storage.UpsertParticipantAsync(new Participant { UserId = "u1", DisplayName = "User 1", Email = "u1@test.com", CurrentLevel = BadgeLevel.Greenhorn, CreatedAt = DateTime.UtcNow });
        await storage.UpsertParticipantAsync(new Participant { UserId = "u2", DisplayName = "User 2", Email = "u2@test.com", CurrentLevel = BadgeLevel.Wayfinder, CreatedAt = DateTime.UtcNow });
        await storage.UpsertParticipantAsync(new Participant { UserId = "u3", DisplayName = "User 3", Email = "u3@test.com", CurrentLevel = BadgeLevel.Wayfinder, CreatedAt = DateTime.UtcNow });
        await storage.UpsertParticipantAsync(new Participant { UserId = "u4", DisplayName = "User 4", Email = "u4@test.com", CurrentLevel = BadgeLevel.TrailGuide, CreatedAt = DateTime.UtcNow });
        await storage.UpsertParticipantAsync(new Participant { UserId = "u5", DisplayName = "User 5", Email = "u5@test.com", CurrentLevel = BadgeLevel.Pioneer, CreatedAt = DateTime.UtcNow });

        var stats = await adminSvc.GetProgramStatsAsync();
        Assert.Equal(5, stats.TotalParticipants);
        Assert.Equal(1, stats.LevelCounts["Greenhorn"]);
        Assert.Equal(2, stats.LevelCounts["Wayfinder"]);
        Assert.Equal(1, stats.LevelCounts["TrailGuide"]);
        Assert.Equal(1, stats.LevelCounts["Pioneer"]);
        // Wayfinder+ = 4/5 = 80%
        Assert.Equal(80.0, stats.WayfinderPercentage);
    }

    [Fact]
    public async Task GetPendingSubmissions_SortedByDate()
    {
        var storage = new InMemoryStorage();
        var adminSvc = new AdminService(storage);

        await storage.UpsertLevelSubmissionAsync(new LevelSubmission
        {
            UserId = "u2", Level = BadgeLevel.Greenhorn,
            IsSubmitted = true, SubmittedAt = DateTime.UtcNow.AddDays(-1)
        });
        await storage.UpsertLevelSubmissionAsync(new LevelSubmission
        {
            UserId = "u1", Level = BadgeLevel.Greenhorn,
            IsSubmitted = true, SubmittedAt = DateTime.UtcNow.AddDays(-3)
        });

        var pending = await adminSvc.GetPendingSubmissionsAsync();
        Assert.Equal(2, pending.Count);
        Assert.Equal("u1", pending[0].UserId); // oldest first
        Assert.Equal("u2", pending[1].UserId);
    }

    [Fact]
    public async Task GetAllParticipants_SearchFilter_Works()
    {
        var storage = new InMemoryStorage();
        var adminSvc = new AdminService(storage);

        await storage.UpsertParticipantAsync(new Participant { UserId = "u1", DisplayName = "Alice Smith", Email = "alice@test.com", Team = "Team A", CurrentLevel = BadgeLevel.Greenhorn, CreatedAt = DateTime.UtcNow });
        await storage.UpsertParticipantAsync(new Participant { UserId = "u2", DisplayName = "Bob Jones", Email = "bob@test.com", Team = "Team B", CurrentLevel = BadgeLevel.Wayfinder, CreatedAt = DateTime.UtcNow });

        var all = await adminSvc.GetAllParticipantsAsync(null);
        Assert.Equal(2, all.Count);

        var filtered = await adminSvc.GetAllParticipantsAsync("Alice");
        Assert.Single(filtered);
        Assert.Equal("Alice Smith", filtered[0].DisplayName);

        var byTeam = await adminSvc.GetAllParticipantsAsync("Team B");
        Assert.Single(byTeam);
        Assert.Equal("Bob Jones", byTeam[0].DisplayName);
    }
}
