// Generated by AI on 05/11/2026
using AiTrailTracker.Api.Models;
using AiTrailTracker.Api.Services;
using AiTrailTracker.Api.Storage;

namespace AiTrailTracker.Api.Tests;

public class SubmitAndLockingTests
{
    private static async Task<(ParticipantService service, InMemoryStorage storage)> SetupWithEvidence()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);

        // Create participant
        await service.GetOrCreateParticipantAsync("user-1", "Test User", "test@example.com");

        // Get criteria for Greenhorn and save evidence for all
        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);
        foreach (var c in criteria)
        {
            await service.SaveEvidenceAsync("user-1", c.Id,
                new List<string> { "https://github.com/org/repo" }, "notes");
        }

        return (service, storage);
    }

    [Fact]
    public async Task SubmitLevel_AllCriteriaHaveEvidence_Succeeds()
    {
        var (service, _) = await SetupWithEvidence();
        await service.SubmitLevelForReviewAsync("user-1");

        var evidence = await service.GetEvidenceForCurrentLevelAsync("user-1");
        Assert.All(evidence, e => Assert.Equal(CriterionStatus.EvidenceSubmitted, e.Status));
    }

    [Fact]
    public async Task SubmitLevel_MissingEvidence_Returns400()
    {
        var storage = new InMemoryStorage();
        var service = new ParticipantService(storage);
        await service.GetOrCreateParticipantAsync("user-1", "Test User", "test@example.com");

        // Don't save any evidence
        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => service.SubmitLevelForReviewAsync("user-1"));
        Assert.Contains("Missing evidence", ex.Message);
    }

    [Fact]
    public async Task SaveEvidence_AfterSubmission_RejectsEdit()
    {
        var (service, _) = await SetupWithEvidence();
        await service.SubmitLevelForReviewAsync("user-1");

        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => service.SaveEvidenceAsync("user-1", criteria[0].Id,
                new List<string> { "https://github.com/updated" }, "updated notes"));
        Assert.Contains("Cannot edit", ex.Message);
    }

    [Fact]
    public async Task SaveEvidence_RejectedCriterion_AllowsEdit()
    {
        var (service, storage) = await SetupWithEvidence();
        await service.SubmitLevelForReviewAsync("user-1");

        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);
        var criterionId = criteria[0].Id;

        // Simulate admin rejecting the criterion
        var evidence = await storage.GetEvidenceAsync("user-1", criterionId);
        evidence!.Status = CriterionStatus.Rejected;
        evidence.AdminFeedback = "Please resubmit";
        await storage.UpsertEvidenceAsync(evidence);

        // Now editing should succeed
        await service.SaveEvidenceAsync("user-1", criterionId,
            new List<string> { "https://github.com/updated" }, "fixed notes");

        var updated = await storage.GetEvidenceAsync("user-1", criterionId);
        Assert.Equal("https://github.com/updated", updated!.EvidenceLinks[0]);
        Assert.Equal(CriterionStatus.InProgress, updated.Status);
    }

    [Fact]
    public async Task SaveEvidence_ApprovedCriterion_StaysLocked()
    {
        var (service, storage) = await SetupWithEvidence();
        await service.SubmitLevelForReviewAsync("user-1");

        var criteria = InMemoryStorage.GetExitCriteria(BadgeLevel.Greenhorn);
        var criterionId = criteria[0].Id;

        // Simulate admin approving the criterion
        var evidence = await storage.GetEvidenceAsync("user-1", criterionId);
        evidence!.Status = CriterionStatus.Approved;
        await storage.UpsertEvidenceAsync(evidence);

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(
            () => service.SaveEvidenceAsync("user-1", criterionId,
                new List<string> { "https://github.com/should-fail" }, "nope"));
        Assert.Contains("Cannot edit", ex.Message);
    }
}
