// Generated by AI on 05/12/2026
using AiTrailTracker.Api.Models;
using AiTrailTracker.Api.Services;
using AiTrailTracker.Api.Storage;

namespace AiTrailTracker.Api.Tests;

public class TeamProgressTests
{
    [Fact]
    public async Task GetTeamProgress_EmptyStorage_ReturnsEmptyList()
    {
        var storage = new InMemoryStorage();
        var svc = new AdminService(storage);

        var result = await svc.GetTeamProgressAsync();
        Assert.Empty(result);
    }

    [Fact]
    public async Task GetTeamProgress_MultipleTeams_GroupsCorrectly()
    {
        var storage = new InMemoryStorage();
        var svc = new AdminService(storage);

        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "u1", DisplayName = "Alice", Email = "a@test.com",
            Team = "Platform", CurrentLevel = BadgeLevel.Greenhorn,
            CreatedAt = DateTime.UtcNow
        });
        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "u2", DisplayName = "Bob", Email = "b@test.com",
            Team = "Platform", CurrentLevel = BadgeLevel.Wayfinder,
            CreatedAt = DateTime.UtcNow
        });
        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "u3", DisplayName = "Carol", Email = "c@test.com",
            Team = "Payments", CurrentLevel = BadgeLevel.TrailGuide,
            CreatedAt = DateTime.UtcNow
        });

        var result = await svc.GetTeamProgressAsync();

        Assert.Equal(2, result.Count);

        var payments = result.Single(t => t.TeamName == "Payments");
        Assert.Equal(1, payments.MemberCount);
        Assert.Equal(1, payments.LevelCounts["TrailGuide"]);

        var platform = result.Single(t => t.TeamName == "Platform");
        Assert.Equal(2, platform.MemberCount);
        Assert.Equal(1, platform.LevelCounts["Greenhorn"]);
        Assert.Equal(1, platform.LevelCounts["Wayfinder"]);
    }

    [Fact]
    public async Task GetTeamProgress_MixedLevels_CorrectLevelCounts()
    {
        var storage = new InMemoryStorage();
        var svc = new AdminService(storage);

        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "u1", DisplayName = "A", Email = "a@t.com",
            Team = "Core", CurrentLevel = BadgeLevel.Greenhorn, CreatedAt = DateTime.UtcNow
        });
        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "u2", DisplayName = "B", Email = "b@t.com",
            Team = "Core", CurrentLevel = BadgeLevel.Wayfinder, CreatedAt = DateTime.UtcNow
        });
        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "u3", DisplayName = "C", Email = "c@t.com",
            Team = "Core", CurrentLevel = BadgeLevel.Pioneer, CreatedAt = DateTime.UtcNow
        });

        var result = await svc.GetTeamProgressAsync();
        var core = result.Single(t => t.TeamName == "Core");

        Assert.Equal(1, core.LevelCounts["Greenhorn"]);
        Assert.Equal(1, core.LevelCounts["Wayfinder"]);
        Assert.Equal(0, core.LevelCounts["TrailGuide"]);
        Assert.Equal(1, core.LevelCounts["Pioneer"]);
    }

    [Fact]
    public async Task GetTeamProgress_StalledParticipant_MarkedAsStalled()
    {
        var storage = new InMemoryStorage();
        var svc = new AdminService(storage);

        // Created 30 days ago, no evidence — should be stalled
        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "u1", DisplayName = "Stalled User", Email = "s@t.com",
            Team = "Alpha", CurrentLevel = BadgeLevel.Greenhorn,
            CreatedAt = DateTime.UtcNow.AddDays(-30)
        });

        var result = await svc.GetTeamProgressAsync();
        var member = result.Single().Members.Single();

        Assert.True(member.IsStalled);
        Assert.True(member.DaysAtCurrentLevel >= 30);
    }

    [Fact]
    public async Task GetTeamProgress_ActiveParticipant_NotStalled()
    {
        var storage = new InMemoryStorage();
        var svc = new AdminService(storage);

        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "u1", DisplayName = "Active User", Email = "a@t.com",
            Team = "Beta", CurrentLevel = BadgeLevel.Greenhorn,
            CreatedAt = DateTime.UtcNow.AddDays(-30)
        });

        // Recent evidence submission
        await storage.UpsertEvidenceAsync(new EvidenceSubmission
        {
            UserId = "u1", CriterionId = "greenhorn-1",
            Level = BadgeLevel.Greenhorn,
            EvidenceLinks = new List<string> { "https://github.com/test" },
            SubmittedAt = DateTime.UtcNow.AddDays(-2)
        });

        var result = await svc.GetTeamProgressAsync();
        var member = result.Single().Members.Single();

        Assert.False(member.IsStalled);
    }

    [Fact]
    public async Task GetTeamProgress_RecentlyCreated_NotStalled()
    {
        var storage = new InMemoryStorage();
        var svc = new AdminService(storage);

        // Created just now, no evidence — not stalled (only 0 days at level)
        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "u1", DisplayName = "New User", Email = "n@t.com",
            Team = "Gamma", CurrentLevel = BadgeLevel.Greenhorn,
            CreatedAt = DateTime.UtcNow
        });

        var result = await svc.GetTeamProgressAsync();
        var member = result.Single().Members.Single();

        Assert.False(member.IsStalled);
    }

    [Fact]
    public async Task GetTeamProgress_EmptyTeam_GroupedAsUnassigned()
    {
        var storage = new InMemoryStorage();
        var svc = new AdminService(storage);

        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "u1", DisplayName = "No Team", Email = "n@t.com",
            Team = "", CurrentLevel = BadgeLevel.Greenhorn,
            CreatedAt = DateTime.UtcNow
        });
        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "u2", DisplayName = "Also No Team", Email = "a@t.com",
            Team = "  ", CurrentLevel = BadgeLevel.Wayfinder,
            CreatedAt = DateTime.UtcNow
        });

        var result = await svc.GetTeamProgressAsync();

        Assert.Single(result);
        Assert.Equal("Unassigned", result[0].TeamName);
        Assert.Equal(2, result[0].MemberCount);
    }

    [Fact]
    public async Task GetTeamProgress_UsesLastAdvancementDate_ForDaysAtLevel()
    {
        var storage = new InMemoryStorage();
        var svc = new AdminService(storage);

        await storage.UpsertParticipantAsync(new Participant
        {
            UserId = "u1", DisplayName = "Advanced", Email = "a@t.com",
            Team = "Delta", CurrentLevel = BadgeLevel.Wayfinder,
            CreatedAt = DateTime.UtcNow.AddDays(-60),
            LastAdvancementAt = DateTime.UtcNow.AddDays(-5)
        });

        var result = await svc.GetTeamProgressAsync();
        var member = result.Single().Members.Single();

        // Should be ~5 days, not 60
        Assert.True(member.DaysAtCurrentLevel >= 5);
        Assert.True(member.DaysAtCurrentLevel < 10);
    }
}
