// Generated by AI on 05/11/2026
using AiTrailTracker.Api.Validation;

namespace AiTrailTracker.Api.Tests;

public class UrlValidatorTests
{
    [Theory]
    [InlineData("https://github.com/org/repo/tree/branch")]
    [InlineData("https://webex.com/recording/12345")]
    [InlineData("http://training-portal.example.com/course")]
    [InlineData("https://learn.microsoft.com/en-us/training/modules/copilot")]
    public void IsValidUrl_ValidUrls_ReturnsTrue(string url)
    {
        Assert.True(UrlValidator.IsValidUrl(url));
    }

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData("not-a-url")]
    [InlineData("ftp://files.example.com/doc")]
    [InlineData("javascript:alert('xss')")]
    [InlineData("data:text/html,<script>alert(1)</script>")]
    [InlineData("github.com/repo")]
    public void IsValidUrl_InvalidUrls_ReturnsFalse(string url)
    {
        Assert.False(UrlValidator.IsValidUrl(url));
    }

    [Fact]
    public void ValidateEvidenceLinks_AllValid_ReturnsNoErrors()
    {
        var links = new List<string>
        {
            "https://github.com/org/repo",
            "https://webex.com/recording/123",
        };
        var errors = UrlValidator.ValidateEvidenceLinks(links);
        Assert.Empty(errors);
    }

    [Fact]
    public void ValidateEvidenceLinks_ContainsInvalid_ReturnsErrors()
    {
        var links = new List<string>
        {
            "https://github.com/org/repo",
            "javascript:alert('xss')",
            "",
        };
        var errors = UrlValidator.ValidateEvidenceLinks(links);
        Assert.Equal(2, errors.Count);
    }
}
