// Generated by AI on 05/10/2026
using AiTrailTracker.Api.Models;
using AiTrailTracker.Api.Storage;

namespace AiTrailTracker.Api.Services;

public class AdminService : IAdminService
{
    private readonly ITrailStorage _storage;

    public AdminService(ITrailStorage storage)
    {
        _storage = storage;
    }

    public async Task<List<LevelSubmission>> GetPendingSubmissionsAsync()
    {
        return await _storage.GetPendingSubmissionsAsync();
    }

    public async Task<List<Participant>> GetAllParticipantsAsync(string? search)
    {
        var participants = await _storage.GetAllParticipantsAsync();
        if (!string.IsNullOrWhiteSpace(search))
        {
            participants = participants
                .Where(p => p.DisplayName.Contains(search, StringComparison.OrdinalIgnoreCase)
                         || p.Email.Contains(search, StringComparison.OrdinalIgnoreCase)
                         || p.Team.Contains(search, StringComparison.OrdinalIgnoreCase))
                .ToList();
        }
        return participants;
    }

    public async Task<Participant?> GetParticipantAsync(string userId)
    {
        return await _storage.GetParticipantAsync(userId);
    }

    public async Task<List<EvidenceSubmission>> GetEvidenceForUserLevelAsync(string userId, BadgeLevel level)
    {
        return await _storage.GetEvidenceByUserAndLevelAsync(userId, level);
    }

    public async Task ApproveEvidenceAsync(string userId, string criterionId, string adminUserId)
    {
        var evidence = await _storage.GetEvidenceAsync(userId, criterionId)
            ?? throw new InvalidOperationException("Evidence submission not found.");

        evidence.Status = CriterionStatus.Approved;
        evidence.ReviewedAt = DateTime.UtcNow;
        evidence.ReviewedBy = adminUserId;
        await _storage.UpsertEvidenceAsync(evidence);
    }

    public async Task RejectEvidenceAsync(string userId, string criterionId, string adminUserId, string feedback)
    {
        if (string.IsNullOrWhiteSpace(feedback))
            throw new ArgumentException("Feedback is required when rejecting evidence.");

        var evidence = await _storage.GetEvidenceAsync(userId, criterionId)
            ?? throw new InvalidOperationException("Evidence submission not found.");

        evidence.Status = CriterionStatus.Rejected;
        evidence.AdminFeedback = feedback;
        evidence.ReviewedAt = DateTime.UtcNow;
        evidence.ReviewedBy = adminUserId;
        await _storage.UpsertEvidenceAsync(evidence);
    }

    public async Task AdvanceParticipantAsync(string userId, string adminUserId)
    {
        var participant = await _storage.GetParticipantAsync(userId)
            ?? throw new InvalidOperationException("Participant not found.");

        if (participant.CurrentLevel == BadgeLevel.Pioneer)
            throw new InvalidOperationException("Pioneer is the highest level.");

        // Verify all criteria for current level are approved
        var criteria = InMemoryStorage.GetExitCriteria(participant.CurrentLevel);
        var evidence = await _storage.GetEvidenceByUserAndLevelAsync(userId, participant.CurrentLevel);

        foreach (var criterion in criteria)
        {
            var submission = evidence.FirstOrDefault(e => e.CriterionId == criterion.Id);
            if (submission == null || submission.Status != CriterionStatus.Approved)
                throw new InvalidOperationException($"Criterion '{criterion.Title}' is not yet approved.");
        }

        // Mark level submission as approved
        var levelSubmission = await _storage.GetLevelSubmissionAsync(userId, participant.CurrentLevel)
            ?? throw new InvalidOperationException("Level submission not found.");

        levelSubmission.IsApproved = true;
        levelSubmission.ApprovedAt = DateTime.UtcNow;
        levelSubmission.ApprovedBy = adminUserId;
        await _storage.UpsertLevelSubmissionAsync(levelSubmission);

        // Advance participant
        participant.CurrentLevel = (BadgeLevel)((int)participant.CurrentLevel + 1);
        participant.LastAdvancementAt = DateTime.UtcNow;
        await _storage.UpsertParticipantAsync(participant);
    }

    public async Task<ProgramStats> GetProgramStatsAsync()
    {
        var participants = await _storage.GetAllParticipantsAsync();
        var pending = await _storage.GetPendingSubmissionsAsync();

        var levelCounts = new Dictionary<string, int>
        {
            ["Greenhorn"] = participants.Count(p => p.CurrentLevel == BadgeLevel.Greenhorn),
            ["Wayfinder"] = participants.Count(p => p.CurrentLevel == BadgeLevel.Wayfinder),
            ["TrailGuide"] = participants.Count(p => p.CurrentLevel == BadgeLevel.TrailGuide),
            ["Pioneer"] = participants.Count(p => p.CurrentLevel == BadgeLevel.Pioneer),
        };

        var total = participants.Count;
        var wayfinderOrAbove = participants.Count(p => p.CurrentLevel >= BadgeLevel.Wayfinder);
        var pct = total > 0 ? Math.Round((double)wayfinderOrAbove / total * 100, 1) : 0;

        return new ProgramStats(total, levelCounts, pct, pending.Count);
    }
}
