// Generated by AI on 05/10/2026
// Modified by AI on 05/12/2026. Edit #1.
using AiTrailTracker.Api.Models;

namespace AiTrailTracker.Api.Services;

public interface IAdminService
{
    Task<List<LevelSubmission>> GetPendingSubmissionsAsync();
    Task<List<Participant>> GetAllParticipantsAsync(string? search);
    Task<Participant?> GetParticipantAsync(string userId);
    Task<List<EvidenceSubmission>> GetEvidenceForUserLevelAsync(string userId, BadgeLevel level);
    Task ApproveEvidenceAsync(string userId, string criterionId, string adminUserId);
    Task RejectEvidenceAsync(string userId, string criterionId, string adminUserId, string feedback);
    Task AdvanceParticipantAsync(string userId, string adminUserId);
    Task<ProgramStats> GetProgramStatsAsync();
    Task<List<TeamProgressDto>> GetTeamProgressAsync();
}
