// Generated by AI on 05/10/2026
// Modified by AI on 05/11/2026. Edit #1.
using AiTrailTracker.Api.Models;

namespace AiTrailTracker.Api.Services;

public interface IParticipantService
{
    Task<Participant> GetOrCreateParticipantAsync(string userId, string displayName, string email);
    Task<List<ExitCriterion>> GetCriteriaForLevelAsync(BadgeLevel level);
    Task<List<EvidenceSubmission>> GetEvidenceForCurrentLevelAsync(string userId);
    Task SaveEvidenceAsync(string userId, string criterionId, List<string> evidenceLinks, string? notes);
    Task SubmitLevelForReviewAsync(string userId);
    Task<List<LevelSubmission>> GetLevelHistoryAsync(string userId);
    Task<List<TrainingLink>> GetTrainingLinksAsync(BadgeLevel level);
    Task<List<PioneerActivityLog>> GetActivityLogsAsync(string userId);
    Task AddActivityLogAsync(string userId, string description, string category);
}
