// Generated by AI on 05/10/2026
using AiTrailTracker.Api.Models;
using AiTrailTracker.Api.Storage;

namespace AiTrailTracker.Api.Services;

public class ParticipantService : IParticipantService
{
    private readonly ITrailStorage _storage;

    public ParticipantService(ITrailStorage storage)
    {
        _storage = storage;
    }

    public async Task<Participant> GetOrCreateParticipantAsync(string userId, string displayName, string email)
    {
        var participant = await _storage.GetParticipantAsync(userId);
        if (participant != null) return participant;

        participant = new Participant
        {
            UserId = userId,
            DisplayName = displayName,
            Email = email,
            CurrentLevel = BadgeLevel.Greenhorn,
            CreatedAt = DateTime.UtcNow,
        };
        await _storage.UpsertParticipantAsync(participant);
        return participant;
    }

    public Task<List<ExitCriterion>> GetCriteriaForLevelAsync(BadgeLevel level)
    {
        return Task.FromResult(InMemoryStorage.GetExitCriteria(level));
    }

    public async Task<List<EvidenceSubmission>> GetEvidenceForCurrentLevelAsync(string userId)
    {
        var participant = await _storage.GetParticipantAsync(userId);
        if (participant == null) return new List<EvidenceSubmission>();

        return await _storage.GetEvidenceByUserAndLevelAsync(userId, participant.CurrentLevel);
    }

    public async Task SaveEvidenceAsync(string userId, string criterionId, List<string> evidenceLinks, string? notes)
    {
        var participant = await _storage.GetParticipantAsync(userId)
            ?? throw new InvalidOperationException("Participant not found.");

        // Verify criterion belongs to current level
        var criteria = InMemoryStorage.GetExitCriteria(participant.CurrentLevel);
        if (!criteria.Any(c => c.Id == criterionId))
            throw new InvalidOperationException("Criterion does not belong to current level.");

        // Check if level is already submitted and not rejected
        var levelSubmission = await _storage.GetLevelSubmissionAsync(userId, participant.CurrentLevel);
        if (levelSubmission is { IsSubmitted: true, IsApproved: false })
        {
            // Check if this specific criterion was rejected — only then allow edit
            var existing = await _storage.GetEvidenceAsync(userId, criterionId);
            if (existing != null && existing.Status != CriterionStatus.Rejected)
                throw new InvalidOperationException("Level is submitted and this criterion is not rejected. Cannot edit.");
        }

        var evidence = await _storage.GetEvidenceAsync(userId, criterionId) ?? new EvidenceSubmission
        {
            UserId = userId,
            CriterionId = criterionId,
            Level = participant.CurrentLevel,
        };

        evidence.EvidenceLinks = evidenceLinks;
        evidence.Notes = notes ?? string.Empty;
        evidence.Status = CriterionStatus.InProgress;
        evidence.AdminFeedback = null;

        await _storage.UpsertEvidenceAsync(evidence);
    }

    public async Task SubmitLevelForReviewAsync(string userId)
    {
        var participant = await _storage.GetParticipantAsync(userId)
            ?? throw new InvalidOperationException("Participant not found.");

        if (participant.CurrentLevel == BadgeLevel.Pioneer)
            throw new InvalidOperationException("Pioneer is the highest level.");

        var criteria = InMemoryStorage.GetExitCriteria(participant.CurrentLevel);
        var evidence = await _storage.GetEvidenceByUserAndLevelAsync(userId, participant.CurrentLevel);

        // Check all criteria have evidence
        foreach (var criterion in criteria)
        {
            var submission = evidence.FirstOrDefault(e => e.CriterionId == criterion.Id);
            if (submission == null || submission.EvidenceLinks.Count == 0)
                throw new InvalidOperationException($"Missing evidence for criterion: {criterion.Title}");
        }

        // Mark all evidence as submitted
        foreach (var e in evidence)
        {
            if (e.Status != CriterionStatus.Approved)
            {
                e.Status = CriterionStatus.EvidenceSubmitted;
                e.SubmittedAt = DateTime.UtcNow;
                await _storage.UpsertEvidenceAsync(e);
            }
        }

        // Create/update level submission
        var levelSubmission = await _storage.GetLevelSubmissionAsync(userId, participant.CurrentLevel)
            ?? new LevelSubmission
            {
                UserId = userId,
                Level = participant.CurrentLevel,
            };

        levelSubmission.IsSubmitted = true;
        levelSubmission.SubmittedAt = DateTime.UtcNow;
        await _storage.UpsertLevelSubmissionAsync(levelSubmission);
    }

    public async Task<List<LevelSubmission>> GetLevelHistoryAsync(string userId)
    {
        return await _storage.GetSubmissionsByUserAsync(userId);
    }

    public async Task<List<TrainingLink>> GetTrainingLinksAsync(BadgeLevel level)
    {
        return await _storage.GetTrainingLinksAsync(level);
    }

    public async Task<List<PioneerActivityLog>> GetActivityLogsAsync(string userId)
    {
        return await _storage.GetActivityLogsAsync(userId);
    }

    public async Task AddActivityLogAsync(string userId, string description, string category)
    {
        var participant = await _storage.GetParticipantAsync(userId)
            ?? throw new InvalidOperationException("Participant not found.");

        if (participant.CurrentLevel != BadgeLevel.Pioneer)
            throw new InvalidOperationException("Activity logs are only available for Pioneers.");

        var log = new PioneerActivityLog
        {
            UserId = userId,
            Date = DateTime.UtcNow,
            Description = description,
            Category = category,
        };

        await _storage.AddActivityLogAsync(log);
    }
}
