// Generated by AI on 05/11/2026
import { render, screen } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import App from './App';

// Mock the API hooks
vi.mock('./api/participantApi', () => ({
  useMe: () => ({ data: { userId: 'test-1', displayName: 'Test User', email: 'test@test.com', currentLevel: 'Greenhorn', isAdmin: false }, isLoading: false }),
  useCriteria: () => ({ data: [] }),
  useEvidence: () => ({ data: [] }),
  useTrainingLinks: () => ({ data: [] }),
  useSaveEvidence: () => ({ mutate: vi.fn() }),
  useSubmitLevel: () => ({ mutate: vi.fn(), isError: false }),
  useActivityLogs: () => ({ data: [] }),
  useAddActivityLog: () => ({ mutate: vi.fn() }),
}));

describe('App', () => {
  it('renders without crashing', () => {
    render(<App />);
    expect(screen.getByText('AI Trail Tracker')).toBeInTheDocument();
  });

  it('displays user name in nav bar', () => {
    render(<App />);
    expect(screen.getByText('Test User')).toBeInTheDocument();
  });
});
