// Generated by AI on 05/12/2026
import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import { MemoryRouter } from 'react-router-dom';
import TeamCard from './components/TeamCard';
import TeamProgressPage from './pages/TeamProgressPage';
import type { TeamProgressDto } from './types';

const mockTeam: TeamProgressDto = {
  teamName: 'Platform',
  memberCount: 3,
  levelCounts: { Greenhorn: 1, Wayfinder: 1, TrailGuide: 1, Pioneer: 0 },
  members: [
    { userId: 'u1', displayName: 'Alice', currentLevel: 'Greenhorn', daysAtCurrentLevel: 5, lastEvidenceDate: '2026-05-10T00:00:00Z', isStalled: false },
    { userId: 'u2', displayName: 'Bob', currentLevel: 'Wayfinder', daysAtCurrentLevel: 20, lastEvidenceDate: null, isStalled: true },
    { userId: 'u3', displayName: 'Carol', currentLevel: 'TrailGuide', daysAtCurrentLevel: 3, lastEvidenceDate: '2026-05-11T00:00:00Z', isStalled: false },
  ],
};

const mockTeams: TeamProgressDto[] = [
  mockTeam,
  {
    teamName: 'Payments',
    memberCount: 1,
    levelCounts: { Greenhorn: 0, Wayfinder: 0, TrailGuide: 0, Pioneer: 1 },
    members: [
      { userId: 'u4', displayName: 'Dave', currentLevel: 'Pioneer', daysAtCurrentLevel: 10, lastEvidenceDate: '2026-05-08T00:00:00Z', isStalled: false },
    ],
  },
];

vi.mock('./api/adminApi', () => ({
  useTeamProgress: () => ({ data: mockTeams, isLoading: false }),
}));

describe('TeamCard', () => {
  it('renders team name and member count', () => {
    render(
      <MemoryRouter>
        <TeamCard team={mockTeam} />
      </MemoryRouter>
    );
    expect(screen.getByText('Platform')).toBeInTheDocument();
    expect(screen.getByText('3 members')).toBeInTheDocument();
  });

  it('shows stalled indicator for stalled members when expanded', () => {
    render(
      <MemoryRouter>
        <TeamCard team={mockTeam} />
      </MemoryRouter>
    );
    // Expand the accordion
    fireEvent.click(screen.getByText('Platform'));
    expect(screen.getByText('Stalled')).toBeInTheDocument();
    expect(screen.getByText('Bob')).toBeInTheDocument();
  });

  it('shows active indicator for non-stalled members when expanded', () => {
    render(
      <MemoryRouter>
        <TeamCard team={mockTeam} />
      </MemoryRouter>
    );
    fireEvent.click(screen.getByText('Platform'));
    const activeChips = screen.getAllByText('Active');
    expect(activeChips.length).toBe(2);
  });
});

describe('TeamProgressPage', () => {
  it('renders page title and team cards', () => {
    render(
      <MemoryRouter>
        <TeamProgressPage />
      </MemoryRouter>
    );
    expect(screen.getByText('Team Progress')).toBeInTheDocument();
    expect(screen.getByText('Platform')).toBeInTheDocument();
    expect(screen.getByText('Payments')).toBeInTheDocument();
  });

  it('filters teams by name', () => {
    render(
      <MemoryRouter>
        <TeamProgressPage />
      </MemoryRouter>
    );
    const input = screen.getByPlaceholderText('Filter by team name...');
    fireEvent.change(input, { target: { value: 'pay' } });
    expect(screen.getByText('Payments')).toBeInTheDocument();
    expect(screen.queryByText('Platform')).not.toBeInTheDocument();
  });

  it('shows no teams message when filter has no matches', () => {
    render(
      <MemoryRouter>
        <TeamProgressPage />
      </MemoryRouter>
    );
    const input = screen.getByPlaceholderText('Filter by team name...');
    fireEvent.change(input, { target: { value: 'nonexistent' } });
    expect(screen.getByText('No teams found.')).toBeInTheDocument();
  });
});
